/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: television.proto */

#ifndef PROTOBUF_C_television_2eproto__INCLUDED
#define PROTOBUF_C_television_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "schema/common/common.pb-c.h"

typedef struct _Iot__Service__Television__Channel Iot__Service__Television__Channel;
typedef struct _Iot__Service__Television__ActionInGetPictureList Iot__Service__Television__ActionInGetPictureList;
typedef struct _Iot__Service__Television__ActionOutGetPictureList Iot__Service__Television__ActionOutGetPictureList;
typedef struct _Iot__Service__Television__ActionOutGetPictureList__PictureInfo Iot__Service__Television__ActionOutGetPictureList__PictureInfo;
typedef struct _Iot__Service__Television__ActionInGetRecordList Iot__Service__Television__ActionInGetRecordList;
typedef struct _Iot__Service__Television__ActionOutGetRecordList Iot__Service__Television__ActionOutGetRecordList;
typedef struct _Iot__Service__Television__ActionOutGetRecordList__PictureInfo Iot__Service__Television__ActionOutGetRecordList__PictureInfo;
typedef struct _Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint;
typedef struct _Iot__Service__Television__EventRecordNotify Iot__Service__Television__EventRecordNotify;
typedef struct _Iot__Service__Television__ActionInDelRecordInfo Iot__Service__Television__ActionInDelRecordInfo;
typedef struct _Iot__Service__Television__ActionOutDelRecordInfo Iot__Service__Television__ActionOutDelRecordInfo;
typedef struct _Iot__Service__Television__ActionInDelPictureInfo Iot__Service__Television__ActionInDelPictureInfo;
typedef struct _Iot__Service__Television__ActionOutDelPictureInfo Iot__Service__Television__ActionOutDelPictureInfo;
typedef struct _Iot__Service__Television__ActionInChannelUp Iot__Service__Television__ActionInChannelUp;
typedef struct _Iot__Service__Television__ActionOutChannelUp Iot__Service__Television__ActionOutChannelUp;
typedef struct _Iot__Service__Television__ActionInChannelDown Iot__Service__Television__ActionInChannelDown;
typedef struct _Iot__Service__Television__ActionOutChannelDown Iot__Service__Television__ActionOutChannelDown;
typedef struct _Iot__Service__Television__EventChannelListChange Iot__Service__Television__EventChannelListChange;
typedef struct _Iot__Service__Television__EventParentControlsModeStart Iot__Service__Television__EventParentControlsModeStart;
typedef struct _Iot__Service__Television__EventParentControlsModeStop Iot__Service__Television__EventParentControlsModeStop;
typedef struct _Iot__Service__Television__ActionInGetParentControlPlaylist Iot__Service__Television__ActionInGetParentControlPlaylist;
typedef struct _Iot__Service__Television__ActionOutGetParentControlPlaylist Iot__Service__Television__ActionOutGetParentControlPlaylist;
typedef struct _Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist;
typedef struct _Iot__Service__Television__ActionInGetParentControlTime Iot__Service__Television__ActionInGetParentControlTime;
typedef struct _Iot__Service__Television__ActionOutGetParentControlTime Iot__Service__Television__ActionOutGetParentControlTime;
typedef struct _Iot__Service__Television__ActionInRemainInParentControl Iot__Service__Television__ActionInRemainInParentControl;
typedef struct _Iot__Service__Television__ActionOutRemainInParentControl Iot__Service__Television__ActionOutRemainInParentControl;
typedef struct _Iot__Service__Television__Properties Iot__Service__Television__Properties;


/* --- enums --- */

typedef enum _Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint__EnumRecordType {
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__PICTURE_CHANGE = 0,
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__CRY = 1,
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__STAYING_DOORWAY = 2,
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__PASSING_BY_DOOR = 3,
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__HUMAN_MOTION = 4,
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__ANIMAL_MOTION = 5,
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__CAT_MOTION = 6,
  IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__DOG_MOTION = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE)
} Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint__EnumRecordType;
typedef enum _Iot__Service__Television__EventRecordNotify__EnumMediaType {
  IOT__SERVICE__TELEVISION__EVENT_RECORD_NOTIFY__ENUM_MEDIA_TYPE__PICTURE = 0,
  IOT__SERVICE__TELEVISION__EVENT_RECORD_NOTIFY__ENUM_MEDIA_TYPE__AUDIO = 1,
  IOT__SERVICE__TELEVISION__EVENT_RECORD_NOTIFY__ENUM_MEDIA_TYPE__VIDEO = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__TELEVISION__EVENT_RECORD_NOTIFY__ENUM_MEDIA_TYPE)
} Iot__Service__Television__EventRecordNotify__EnumMediaType;
typedef enum _Iot__Service__Television__EnumSourceInput {
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__VGA = 0,
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__USB1 = 1,
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__USB2 = 2,
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__HDMI1 = 3,
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__HDMI2 = 4,
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__NETWORK = 5,
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__AV = 6,
  IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__SD_CARD = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT)
} Iot__Service__Television__EnumSourceInput;
typedef enum _Iot__Service__Television__Status {
  IOT__SERVICE__TELEVISION__STATUS__IDEL = 0,
  IOT__SERVICE__TELEVISION__STATUS__WORKING = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__TELEVISION__STATUS)
} Iot__Service__Television__Status;
typedef enum _Iot__Service__Television__Sleep {
  IOT__SERVICE__TELEVISION__SLEEP__S_OFF = 0,
  IOT__SERVICE__TELEVISION__SLEEP__S_ON = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__TELEVISION__SLEEP)
} Iot__Service__Television__Sleep;

/* --- messages --- */

struct  _Iot__Service__Television__Channel
{
  ProtobufCMessage base;
  uint32_t channelid;
  char *channelname;
};
#define IOT__SERVICE__TELEVISION__CHANNEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__channel__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


struct  _Iot__Service__Television__ActionInGetPictureList
{
  ProtobufCMessage base;
  uint64_t fromtime;
  uint64_t totime;
  uint32_t count;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_GET_PICTURE_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_get_picture_list__descriptor) \
    , 0, 0, 0 }


struct  _Iot__Service__Television__ActionOutGetPictureList__PictureInfo
{
  ProtobufCMessage base;
  char *filename;
  uint64_t capturetime;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_PICTURE_LIST__PICTURE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_picture_list__picture_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _Iot__Service__Television__ActionOutGetPictureList
{
  ProtobufCMessage base;
  uint32_t totalcount;
  size_t n_pictureinfo;
  Iot__Service__Television__ActionOutGetPictureList__PictureInfo **pictureinfo;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_PICTURE_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_picture_list__descriptor) \
    , 0, 0,NULL }


struct  _Iot__Service__Television__ActionInGetRecordList
{
  ProtobufCMessage base;
  uint64_t fromtime;
  uint64_t totime;
  uint32_t recordcount;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_GET_RECORD_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_get_record_list__descriptor) \
    , 0, 0, 0 }


struct  _Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint
{
  ProtobufCMessage base;
  Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint__EnumRecordType recordtype;
  uint64_t characteristicpoint;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_record_list__picture_info__record_point__descriptor) \
    , IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__RECORD_POINT__ENUM_RECORD_TYPE__PICTURE_CHANGE, 0 }


struct  _Iot__Service__Television__ActionOutGetRecordList__PictureInfo
{
  ProtobufCMessage base;
  char *recordfilename;
  char *thumbnailfilename;
  uint64_t recordstarttime;
  uint32_t recordelapsedtime;
  protobuf_c_boolean autodeleteenabled;
  size_t n_recordpoint;
  Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint **recordpoint;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__PICTURE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_record_list__picture_info__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0, 0,NULL }


struct  _Iot__Service__Television__ActionOutGetRecordList
{
  ProtobufCMessage base;
  uint32_t totalrecordcount;
  size_t n_pictureinfo;
  Iot__Service__Television__ActionOutGetRecordList__PictureInfo **pictureinfo;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_RECORD_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_record_list__descriptor) \
    , 0, 0,NULL }


struct  _Iot__Service__Television__EventRecordNotify
{
  ProtobufCMessage base;
  char *filename;
  Iot__Service__Television__EventRecordNotify__EnumMediaType mediatype;
};
#define IOT__SERVICE__TELEVISION__EVENT_RECORD_NOTIFY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__event_record_notify__descriptor) \
    , (char *)protobuf_c_empty_string, IOT__SERVICE__TELEVISION__EVENT_RECORD_NOTIFY__ENUM_MEDIA_TYPE__PICTURE }


struct  _Iot__Service__Television__ActionInDelRecordInfo
{
  ProtobufCMessage base;
  size_t n_filename;
  char **filename;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_DEL_RECORD_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_del_record_info__descriptor) \
    , 0,NULL }


struct  _Iot__Service__Television__ActionOutDelRecordInfo
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_DEL_RECORD_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_del_record_info__descriptor) \
     }


struct  _Iot__Service__Television__ActionInDelPictureInfo
{
  ProtobufCMessage base;
  size_t n_filename;
  char **filename;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_DEL_PICTURE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_del_picture_info__descriptor) \
    , 0,NULL }


struct  _Iot__Service__Television__ActionOutDelPictureInfo
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_DEL_PICTURE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_del_picture_info__descriptor) \
     }


struct  _Iot__Service__Television__ActionInChannelUp
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_CHANNEL_UP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_channel_up__descriptor) \
     }


struct  _Iot__Service__Television__ActionOutChannelUp
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_CHANNEL_UP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_channel_up__descriptor) \
     }


struct  _Iot__Service__Television__ActionInChannelDown
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_CHANNEL_DOWN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_channel_down__descriptor) \
     }


struct  _Iot__Service__Television__ActionOutChannelDown
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_CHANNEL_DOWN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_channel_down__descriptor) \
     }


struct  _Iot__Service__Television__EventChannelListChange
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__EVENT_CHANNEL_LIST_CHANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__event_channel_list_change__descriptor) \
     }


struct  _Iot__Service__Television__EventParentControlsModeStart
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__EVENT_PARENT_CONTROLS_MODE_START__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__event_parent_controls_mode_start__descriptor) \
     }


struct  _Iot__Service__Television__EventParentControlsModeStop
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__EVENT_PARENT_CONTROLS_MODE_STOP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__event_parent_controls_mode_stop__descriptor) \
     }


struct  _Iot__Service__Television__ActionInGetParentControlPlaylist
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_GET_PARENT_CONTROL_PLAYLIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_get_parent_control_playlist__descriptor) \
     }


struct  _Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist
{
  ProtobufCMessage base;
  char *contentname;
  /*
   *百分比
   */
  uint32_t process;
  /*
   *YYYY-MM-DD hh-mm-ss
   */
  char *playtime;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_PARENT_CONTROL_PLAYLIST__PLAYLIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_parent_control_playlist__playlist__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


struct  _Iot__Service__Television__ActionOutGetParentControlPlaylist
{
  ProtobufCMessage base;
  size_t n_playlist;
  Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist **playlist;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_PARENT_CONTROL_PLAYLIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_parent_control_playlist__descriptor) \
    , 0,NULL }


struct  _Iot__Service__Television__ActionInGetParentControlTime
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_GET_PARENT_CONTROL_TIME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_get_parent_control_time__descriptor) \
     }


struct  _Iot__Service__Television__ActionOutGetParentControlTime
{
  ProtobufCMessage base;
  uint32_t parentcontroltime;
  /*
   *default value ：0
   */
  uint32_t totalparentcontroltime;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_GET_PARENT_CONTROL_TIME__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_get_parent_control_time__descriptor) \
    , 0, 0 }


struct  _Iot__Service__Television__ActionInRemainInParentControl
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_IN_REMAIN_IN_PARENT_CONTROL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_in_remain_in_parent_control__descriptor) \
     }


struct  _Iot__Service__Television__ActionOutRemainInParentControl
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__TELEVISION__ACTION_OUT_REMAIN_IN_PARENT_CONTROL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__action_out_remain_in_parent_control__descriptor) \
     }


struct  _Iot__Service__Television__Properties
{
  ProtobufCMessage base;
  protobuf_c_boolean power;
  Iot__Service__Television__Sleep sleep;
  uint32_t soundvolume;
  protobuf_c_boolean speechcontrolenabled;
  Iot__Service__Television__EnumSourceInput sourceinput;
  Iot__Service__Television__Status status;
  protobuf_c_boolean parentcontrolsenabled;
  uint32_t singlewatchingtvtime;
  protobuf_c_boolean mute;
  char *currentchannel;
  /*
   * action channelUp(ActionInChannelUp) returns (ActionOutChannelUp) = 12;
   * action channelDown(ActionInChannelDown) returns (ActionOutChannelDown) = 13;
   * action getParentControlPlaylist(ActionInGetParentControlPlaylist) returns (ActionOutGetParentControlPlaylist)= 14;
   * action getPictureList(ActionInGetPictureList) returns (stream ActionOutGetPictureList) = 15;  //由被动端发起正常结束事务
   * action getRecordList(ActionInGetRecordList) returns (stream ActionOutGetRecordList) = 16;  //由被动端发起正常结束事务
   * action delRecordInfo(ActionInDelRecordInfo) returns (ActionOutDelRecordInfo) = 17;
   * action delPictureInfo(ActionInDelPictureInfo) returns (ActionOutDelPictureInfo) = 18;
   * event recordNotify(EventRecordNotify) = 19;
   * event channelListChange(EventChannelListChange) = 20;
   * event parentControlsModeStart(EventParentControlsModeStart) = 21;
   * event parentControlsModeStop (EventParentControlsModeStop) = 22;
   * action getParentControlTime(ActionInGetParentControlTime) returns (ActionOutGetParentControlTime) = 23;
   * action remainInParentControl(ActionInRemainInParentControl) returns (ActionOutRemainInParentControl) = 24;
   */
  size_t n_channel;
  ArrayNode **channel;
};
#define IOT__SERVICE__TELEVISION__PROPERTIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__television__properties__descriptor) \
    , 0, IOT__SERVICE__TELEVISION__SLEEP__S_OFF, 0, 0, IOT__SERVICE__TELEVISION__ENUM_SOURCE_INPUT__VGA, IOT__SERVICE__TELEVISION__STATUS__IDEL, 0, 0, 0, (char *)protobuf_c_empty_string, 0,NULL }


/* Iot__Service__Television__Channel methods */
void   iot__service__television__channel__init
                     (Iot__Service__Television__Channel         *message);
size_t iot__service__television__channel__get_packed_size
                     (const Iot__Service__Television__Channel   *message);
size_t iot__service__television__channel__pack
                     (const Iot__Service__Television__Channel   *message,
                      uint8_t             *out);
size_t iot__service__television__channel__pack_to_buffer
                     (const Iot__Service__Television__Channel   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__Channel *
       iot__service__television__channel__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__channel__free_unpacked
                     (Iot__Service__Television__Channel *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInGetPictureList methods */
void   iot__service__television__action_in_get_picture_list__init
                     (Iot__Service__Television__ActionInGetPictureList         *message);
size_t iot__service__television__action_in_get_picture_list__get_packed_size
                     (const Iot__Service__Television__ActionInGetPictureList   *message);
size_t iot__service__television__action_in_get_picture_list__pack
                     (const Iot__Service__Television__ActionInGetPictureList   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_get_picture_list__pack_to_buffer
                     (const Iot__Service__Television__ActionInGetPictureList   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInGetPictureList *
       iot__service__television__action_in_get_picture_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_get_picture_list__free_unpacked
                     (Iot__Service__Television__ActionInGetPictureList *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutGetPictureList__PictureInfo methods */
void   iot__service__television__action_out_get_picture_list__picture_info__init
                     (Iot__Service__Television__ActionOutGetPictureList__PictureInfo         *message);
/* Iot__Service__Television__ActionOutGetPictureList methods */
void   iot__service__television__action_out_get_picture_list__init
                     (Iot__Service__Television__ActionOutGetPictureList         *message);
size_t iot__service__television__action_out_get_picture_list__get_packed_size
                     (const Iot__Service__Television__ActionOutGetPictureList   *message);
size_t iot__service__television__action_out_get_picture_list__pack
                     (const Iot__Service__Television__ActionOutGetPictureList   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_get_picture_list__pack_to_buffer
                     (const Iot__Service__Television__ActionOutGetPictureList   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutGetPictureList *
       iot__service__television__action_out_get_picture_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_get_picture_list__free_unpacked
                     (Iot__Service__Television__ActionOutGetPictureList *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInGetRecordList methods */
void   iot__service__television__action_in_get_record_list__init
                     (Iot__Service__Television__ActionInGetRecordList         *message);
size_t iot__service__television__action_in_get_record_list__get_packed_size
                     (const Iot__Service__Television__ActionInGetRecordList   *message);
size_t iot__service__television__action_in_get_record_list__pack
                     (const Iot__Service__Television__ActionInGetRecordList   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_get_record_list__pack_to_buffer
                     (const Iot__Service__Television__ActionInGetRecordList   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInGetRecordList *
       iot__service__television__action_in_get_record_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_get_record_list__free_unpacked
                     (Iot__Service__Television__ActionInGetRecordList *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint methods */
void   iot__service__television__action_out_get_record_list__picture_info__record_point__init
                     (Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint         *message);
/* Iot__Service__Television__ActionOutGetRecordList__PictureInfo methods */
void   iot__service__television__action_out_get_record_list__picture_info__init
                     (Iot__Service__Television__ActionOutGetRecordList__PictureInfo         *message);
/* Iot__Service__Television__ActionOutGetRecordList methods */
void   iot__service__television__action_out_get_record_list__init
                     (Iot__Service__Television__ActionOutGetRecordList         *message);
size_t iot__service__television__action_out_get_record_list__get_packed_size
                     (const Iot__Service__Television__ActionOutGetRecordList   *message);
size_t iot__service__television__action_out_get_record_list__pack
                     (const Iot__Service__Television__ActionOutGetRecordList   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_get_record_list__pack_to_buffer
                     (const Iot__Service__Television__ActionOutGetRecordList   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutGetRecordList *
       iot__service__television__action_out_get_record_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_get_record_list__free_unpacked
                     (Iot__Service__Television__ActionOutGetRecordList *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__EventRecordNotify methods */
void   iot__service__television__event_record_notify__init
                     (Iot__Service__Television__EventRecordNotify         *message);
size_t iot__service__television__event_record_notify__get_packed_size
                     (const Iot__Service__Television__EventRecordNotify   *message);
size_t iot__service__television__event_record_notify__pack
                     (const Iot__Service__Television__EventRecordNotify   *message,
                      uint8_t             *out);
size_t iot__service__television__event_record_notify__pack_to_buffer
                     (const Iot__Service__Television__EventRecordNotify   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__EventRecordNotify *
       iot__service__television__event_record_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__event_record_notify__free_unpacked
                     (Iot__Service__Television__EventRecordNotify *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInDelRecordInfo methods */
void   iot__service__television__action_in_del_record_info__init
                     (Iot__Service__Television__ActionInDelRecordInfo         *message);
size_t iot__service__television__action_in_del_record_info__get_packed_size
                     (const Iot__Service__Television__ActionInDelRecordInfo   *message);
size_t iot__service__television__action_in_del_record_info__pack
                     (const Iot__Service__Television__ActionInDelRecordInfo   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_del_record_info__pack_to_buffer
                     (const Iot__Service__Television__ActionInDelRecordInfo   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInDelRecordInfo *
       iot__service__television__action_in_del_record_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_del_record_info__free_unpacked
                     (Iot__Service__Television__ActionInDelRecordInfo *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutDelRecordInfo methods */
void   iot__service__television__action_out_del_record_info__init
                     (Iot__Service__Television__ActionOutDelRecordInfo         *message);
size_t iot__service__television__action_out_del_record_info__get_packed_size
                     (const Iot__Service__Television__ActionOutDelRecordInfo   *message);
size_t iot__service__television__action_out_del_record_info__pack
                     (const Iot__Service__Television__ActionOutDelRecordInfo   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_del_record_info__pack_to_buffer
                     (const Iot__Service__Television__ActionOutDelRecordInfo   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutDelRecordInfo *
       iot__service__television__action_out_del_record_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_del_record_info__free_unpacked
                     (Iot__Service__Television__ActionOutDelRecordInfo *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInDelPictureInfo methods */
void   iot__service__television__action_in_del_picture_info__init
                     (Iot__Service__Television__ActionInDelPictureInfo         *message);
size_t iot__service__television__action_in_del_picture_info__get_packed_size
                     (const Iot__Service__Television__ActionInDelPictureInfo   *message);
size_t iot__service__television__action_in_del_picture_info__pack
                     (const Iot__Service__Television__ActionInDelPictureInfo   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_del_picture_info__pack_to_buffer
                     (const Iot__Service__Television__ActionInDelPictureInfo   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInDelPictureInfo *
       iot__service__television__action_in_del_picture_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_del_picture_info__free_unpacked
                     (Iot__Service__Television__ActionInDelPictureInfo *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutDelPictureInfo methods */
void   iot__service__television__action_out_del_picture_info__init
                     (Iot__Service__Television__ActionOutDelPictureInfo         *message);
size_t iot__service__television__action_out_del_picture_info__get_packed_size
                     (const Iot__Service__Television__ActionOutDelPictureInfo   *message);
size_t iot__service__television__action_out_del_picture_info__pack
                     (const Iot__Service__Television__ActionOutDelPictureInfo   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_del_picture_info__pack_to_buffer
                     (const Iot__Service__Television__ActionOutDelPictureInfo   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutDelPictureInfo *
       iot__service__television__action_out_del_picture_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_del_picture_info__free_unpacked
                     (Iot__Service__Television__ActionOutDelPictureInfo *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInChannelUp methods */
void   iot__service__television__action_in_channel_up__init
                     (Iot__Service__Television__ActionInChannelUp         *message);
size_t iot__service__television__action_in_channel_up__get_packed_size
                     (const Iot__Service__Television__ActionInChannelUp   *message);
size_t iot__service__television__action_in_channel_up__pack
                     (const Iot__Service__Television__ActionInChannelUp   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_channel_up__pack_to_buffer
                     (const Iot__Service__Television__ActionInChannelUp   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInChannelUp *
       iot__service__television__action_in_channel_up__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_channel_up__free_unpacked
                     (Iot__Service__Television__ActionInChannelUp *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutChannelUp methods */
void   iot__service__television__action_out_channel_up__init
                     (Iot__Service__Television__ActionOutChannelUp         *message);
size_t iot__service__television__action_out_channel_up__get_packed_size
                     (const Iot__Service__Television__ActionOutChannelUp   *message);
size_t iot__service__television__action_out_channel_up__pack
                     (const Iot__Service__Television__ActionOutChannelUp   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_channel_up__pack_to_buffer
                     (const Iot__Service__Television__ActionOutChannelUp   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutChannelUp *
       iot__service__television__action_out_channel_up__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_channel_up__free_unpacked
                     (Iot__Service__Television__ActionOutChannelUp *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInChannelDown methods */
void   iot__service__television__action_in_channel_down__init
                     (Iot__Service__Television__ActionInChannelDown         *message);
size_t iot__service__television__action_in_channel_down__get_packed_size
                     (const Iot__Service__Television__ActionInChannelDown   *message);
size_t iot__service__television__action_in_channel_down__pack
                     (const Iot__Service__Television__ActionInChannelDown   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_channel_down__pack_to_buffer
                     (const Iot__Service__Television__ActionInChannelDown   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInChannelDown *
       iot__service__television__action_in_channel_down__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_channel_down__free_unpacked
                     (Iot__Service__Television__ActionInChannelDown *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutChannelDown methods */
void   iot__service__television__action_out_channel_down__init
                     (Iot__Service__Television__ActionOutChannelDown         *message);
size_t iot__service__television__action_out_channel_down__get_packed_size
                     (const Iot__Service__Television__ActionOutChannelDown   *message);
size_t iot__service__television__action_out_channel_down__pack
                     (const Iot__Service__Television__ActionOutChannelDown   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_channel_down__pack_to_buffer
                     (const Iot__Service__Television__ActionOutChannelDown   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutChannelDown *
       iot__service__television__action_out_channel_down__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_channel_down__free_unpacked
                     (Iot__Service__Television__ActionOutChannelDown *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__EventChannelListChange methods */
void   iot__service__television__event_channel_list_change__init
                     (Iot__Service__Television__EventChannelListChange         *message);
size_t iot__service__television__event_channel_list_change__get_packed_size
                     (const Iot__Service__Television__EventChannelListChange   *message);
size_t iot__service__television__event_channel_list_change__pack
                     (const Iot__Service__Television__EventChannelListChange   *message,
                      uint8_t             *out);
size_t iot__service__television__event_channel_list_change__pack_to_buffer
                     (const Iot__Service__Television__EventChannelListChange   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__EventChannelListChange *
       iot__service__television__event_channel_list_change__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__event_channel_list_change__free_unpacked
                     (Iot__Service__Television__EventChannelListChange *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__EventParentControlsModeStart methods */
void   iot__service__television__event_parent_controls_mode_start__init
                     (Iot__Service__Television__EventParentControlsModeStart         *message);
size_t iot__service__television__event_parent_controls_mode_start__get_packed_size
                     (const Iot__Service__Television__EventParentControlsModeStart   *message);
size_t iot__service__television__event_parent_controls_mode_start__pack
                     (const Iot__Service__Television__EventParentControlsModeStart   *message,
                      uint8_t             *out);
size_t iot__service__television__event_parent_controls_mode_start__pack_to_buffer
                     (const Iot__Service__Television__EventParentControlsModeStart   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__EventParentControlsModeStart *
       iot__service__television__event_parent_controls_mode_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__event_parent_controls_mode_start__free_unpacked
                     (Iot__Service__Television__EventParentControlsModeStart *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__EventParentControlsModeStop methods */
void   iot__service__television__event_parent_controls_mode_stop__init
                     (Iot__Service__Television__EventParentControlsModeStop         *message);
size_t iot__service__television__event_parent_controls_mode_stop__get_packed_size
                     (const Iot__Service__Television__EventParentControlsModeStop   *message);
size_t iot__service__television__event_parent_controls_mode_stop__pack
                     (const Iot__Service__Television__EventParentControlsModeStop   *message,
                      uint8_t             *out);
size_t iot__service__television__event_parent_controls_mode_stop__pack_to_buffer
                     (const Iot__Service__Television__EventParentControlsModeStop   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__EventParentControlsModeStop *
       iot__service__television__event_parent_controls_mode_stop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__event_parent_controls_mode_stop__free_unpacked
                     (Iot__Service__Television__EventParentControlsModeStop *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInGetParentControlPlaylist methods */
void   iot__service__television__action_in_get_parent_control_playlist__init
                     (Iot__Service__Television__ActionInGetParentControlPlaylist         *message);
size_t iot__service__television__action_in_get_parent_control_playlist__get_packed_size
                     (const Iot__Service__Television__ActionInGetParentControlPlaylist   *message);
size_t iot__service__television__action_in_get_parent_control_playlist__pack
                     (const Iot__Service__Television__ActionInGetParentControlPlaylist   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_get_parent_control_playlist__pack_to_buffer
                     (const Iot__Service__Television__ActionInGetParentControlPlaylist   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInGetParentControlPlaylist *
       iot__service__television__action_in_get_parent_control_playlist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_get_parent_control_playlist__free_unpacked
                     (Iot__Service__Television__ActionInGetParentControlPlaylist *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist methods */
void   iot__service__television__action_out_get_parent_control_playlist__playlist__init
                     (Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist         *message);
/* Iot__Service__Television__ActionOutGetParentControlPlaylist methods */
void   iot__service__television__action_out_get_parent_control_playlist__init
                     (Iot__Service__Television__ActionOutGetParentControlPlaylist         *message);
size_t iot__service__television__action_out_get_parent_control_playlist__get_packed_size
                     (const Iot__Service__Television__ActionOutGetParentControlPlaylist   *message);
size_t iot__service__television__action_out_get_parent_control_playlist__pack
                     (const Iot__Service__Television__ActionOutGetParentControlPlaylist   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_get_parent_control_playlist__pack_to_buffer
                     (const Iot__Service__Television__ActionOutGetParentControlPlaylist   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutGetParentControlPlaylist *
       iot__service__television__action_out_get_parent_control_playlist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_get_parent_control_playlist__free_unpacked
                     (Iot__Service__Television__ActionOutGetParentControlPlaylist *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInGetParentControlTime methods */
void   iot__service__television__action_in_get_parent_control_time__init
                     (Iot__Service__Television__ActionInGetParentControlTime         *message);
size_t iot__service__television__action_in_get_parent_control_time__get_packed_size
                     (const Iot__Service__Television__ActionInGetParentControlTime   *message);
size_t iot__service__television__action_in_get_parent_control_time__pack
                     (const Iot__Service__Television__ActionInGetParentControlTime   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_get_parent_control_time__pack_to_buffer
                     (const Iot__Service__Television__ActionInGetParentControlTime   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInGetParentControlTime *
       iot__service__television__action_in_get_parent_control_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_get_parent_control_time__free_unpacked
                     (Iot__Service__Television__ActionInGetParentControlTime *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutGetParentControlTime methods */
void   iot__service__television__action_out_get_parent_control_time__init
                     (Iot__Service__Television__ActionOutGetParentControlTime         *message);
size_t iot__service__television__action_out_get_parent_control_time__get_packed_size
                     (const Iot__Service__Television__ActionOutGetParentControlTime   *message);
size_t iot__service__television__action_out_get_parent_control_time__pack
                     (const Iot__Service__Television__ActionOutGetParentControlTime   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_get_parent_control_time__pack_to_buffer
                     (const Iot__Service__Television__ActionOutGetParentControlTime   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutGetParentControlTime *
       iot__service__television__action_out_get_parent_control_time__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_get_parent_control_time__free_unpacked
                     (Iot__Service__Television__ActionOutGetParentControlTime *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionInRemainInParentControl methods */
void   iot__service__television__action_in_remain_in_parent_control__init
                     (Iot__Service__Television__ActionInRemainInParentControl         *message);
size_t iot__service__television__action_in_remain_in_parent_control__get_packed_size
                     (const Iot__Service__Television__ActionInRemainInParentControl   *message);
size_t iot__service__television__action_in_remain_in_parent_control__pack
                     (const Iot__Service__Television__ActionInRemainInParentControl   *message,
                      uint8_t             *out);
size_t iot__service__television__action_in_remain_in_parent_control__pack_to_buffer
                     (const Iot__Service__Television__ActionInRemainInParentControl   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionInRemainInParentControl *
       iot__service__television__action_in_remain_in_parent_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_in_remain_in_parent_control__free_unpacked
                     (Iot__Service__Television__ActionInRemainInParentControl *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__ActionOutRemainInParentControl methods */
void   iot__service__television__action_out_remain_in_parent_control__init
                     (Iot__Service__Television__ActionOutRemainInParentControl         *message);
size_t iot__service__television__action_out_remain_in_parent_control__get_packed_size
                     (const Iot__Service__Television__ActionOutRemainInParentControl   *message);
size_t iot__service__television__action_out_remain_in_parent_control__pack
                     (const Iot__Service__Television__ActionOutRemainInParentControl   *message,
                      uint8_t             *out);
size_t iot__service__television__action_out_remain_in_parent_control__pack_to_buffer
                     (const Iot__Service__Television__ActionOutRemainInParentControl   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__ActionOutRemainInParentControl *
       iot__service__television__action_out_remain_in_parent_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__action_out_remain_in_parent_control__free_unpacked
                     (Iot__Service__Television__ActionOutRemainInParentControl *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__Television__Properties methods */
void   iot__service__television__properties__init
                     (Iot__Service__Television__Properties         *message);
size_t iot__service__television__properties__get_packed_size
                     (const Iot__Service__Television__Properties   *message);
size_t iot__service__television__properties__pack
                     (const Iot__Service__Television__Properties   *message,
                      uint8_t             *out);
size_t iot__service__television__properties__pack_to_buffer
                     (const Iot__Service__Television__Properties   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__Television__Properties *
       iot__service__television__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__television__properties__free_unpacked
                     (Iot__Service__Television__Properties *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Iot__Service__Television__Channel_Closure)
                 (const Iot__Service__Television__Channel *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInGetPictureList_Closure)
                 (const Iot__Service__Television__ActionInGetPictureList *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetPictureList__PictureInfo_Closure)
                 (const Iot__Service__Television__ActionOutGetPictureList__PictureInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetPictureList_Closure)
                 (const Iot__Service__Television__ActionOutGetPictureList *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInGetRecordList_Closure)
                 (const Iot__Service__Television__ActionInGetRecordList *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint_Closure)
                 (const Iot__Service__Television__ActionOutGetRecordList__PictureInfo__RecordPoint *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetRecordList__PictureInfo_Closure)
                 (const Iot__Service__Television__ActionOutGetRecordList__PictureInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetRecordList_Closure)
                 (const Iot__Service__Television__ActionOutGetRecordList *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__EventRecordNotify_Closure)
                 (const Iot__Service__Television__EventRecordNotify *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInDelRecordInfo_Closure)
                 (const Iot__Service__Television__ActionInDelRecordInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutDelRecordInfo_Closure)
                 (const Iot__Service__Television__ActionOutDelRecordInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInDelPictureInfo_Closure)
                 (const Iot__Service__Television__ActionInDelPictureInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutDelPictureInfo_Closure)
                 (const Iot__Service__Television__ActionOutDelPictureInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInChannelUp_Closure)
                 (const Iot__Service__Television__ActionInChannelUp *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutChannelUp_Closure)
                 (const Iot__Service__Television__ActionOutChannelUp *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInChannelDown_Closure)
                 (const Iot__Service__Television__ActionInChannelDown *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutChannelDown_Closure)
                 (const Iot__Service__Television__ActionOutChannelDown *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__EventChannelListChange_Closure)
                 (const Iot__Service__Television__EventChannelListChange *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__EventParentControlsModeStart_Closure)
                 (const Iot__Service__Television__EventParentControlsModeStart *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__EventParentControlsModeStop_Closure)
                 (const Iot__Service__Television__EventParentControlsModeStop *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInGetParentControlPlaylist_Closure)
                 (const Iot__Service__Television__ActionInGetParentControlPlaylist *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist_Closure)
                 (const Iot__Service__Television__ActionOutGetParentControlPlaylist__Playlist *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetParentControlPlaylist_Closure)
                 (const Iot__Service__Television__ActionOutGetParentControlPlaylist *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInGetParentControlTime_Closure)
                 (const Iot__Service__Television__ActionInGetParentControlTime *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutGetParentControlTime_Closure)
                 (const Iot__Service__Television__ActionOutGetParentControlTime *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionInRemainInParentControl_Closure)
                 (const Iot__Service__Television__ActionInRemainInParentControl *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__ActionOutRemainInParentControl_Closure)
                 (const Iot__Service__Television__ActionOutRemainInParentControl *message,
                  void *closure_data);
typedef void (*Iot__Service__Television__Properties_Closure)
                 (const Iot__Service__Television__Properties *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    iot__service__television__enum_source_input__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__television__status__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__television__sleep__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__channel__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_get_picture_list__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_picture_list__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_picture_list__picture_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_get_record_list__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_record_list__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_record_list__picture_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_record_list__picture_info__record_point__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__television__action_out_get_record_list__picture_info__record_point__enum_record_type__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__event_record_notify__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__television__event_record_notify__enum_media_type__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_del_record_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_del_record_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_del_picture_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_del_picture_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_channel_up__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_channel_up__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_channel_down__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_channel_down__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__event_channel_list_change__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__event_parent_controls_mode_start__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__event_parent_controls_mode_stop__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_get_parent_control_playlist__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_parent_control_playlist__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_parent_control_playlist__playlist__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_get_parent_control_time__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_get_parent_control_time__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_in_remain_in_parent_control__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__action_out_remain_in_parent_control__descriptor;
extern const ProtobufCMessageDescriptor iot__service__television__properties__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_television_2eproto__INCLUDED */
