/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sf.pb-c.h"
void   iot__service__sf__properties__init
                     (Iot__Service__Sf__Properties         *message)
{
  static const Iot__Service__Sf__Properties init_value = IOT__SERVICE__SF__PROPERTIES__INIT;
  *message = init_value;
}
size_t iot__service__sf__properties__get_packed_size
                     (const Iot__Service__Sf__Properties *message)
{
  assert(message->base.descriptor == &iot__service__sf__properties__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__sf__properties__pack
                     (const Iot__Service__Sf__Properties *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__sf__properties__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__sf__properties__pack_to_buffer
                     (const Iot__Service__Sf__Properties *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__sf__properties__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__Sf__Properties *
       iot__service__sf__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__Sf__Properties *)
     protobuf_c_message_unpack (&iot__service__sf__properties__descriptor,
                                allocator, len, data);
}
void   iot__service__sf__properties__free_unpacked
                     (Iot__Service__Sf__Properties *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__sf__properties__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor iot__service__sf__properties__field_descriptors[20] =
{
  {
    "power",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mannulAutoSta",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, mannulautosta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "faultSta",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, faultsta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pressureDiffSta",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, pressurediffsta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlvOpening",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, vlvopening),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlvFeedback",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, vlvfeedback),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freqSetting",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, freqsetting),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freqFeedback",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, freqfeedback),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentTemperature",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, currenttemperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentTemperature2",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, currenttemperature2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetTemperature",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, targettemperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentHumidity",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, currenthumidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetHumidity",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, targethumidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentPres1",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, currentpres1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentPres2",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, currentpres2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetPres1",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, targetpres1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetPres2",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, targetpres2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minimumFreq",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, minimumfreq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "co2",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, co2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetCo2",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Sf__Properties, targetco2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot__service__sf__properties__field_indices_by_name[] = {
  18,   /* field[18] = co2 */
  11,   /* field[11] = currentHumidity */
  13,   /* field[13] = currentPres1 */
  14,   /* field[14] = currentPres2 */
  8,   /* field[8] = currentTemperature */
  9,   /* field[9] = currentTemperature2 */
  2,   /* field[2] = faultSta */
  7,   /* field[7] = freqFeedback */
  6,   /* field[6] = freqSetting */
  1,   /* field[1] = mannulAutoSta */
  17,   /* field[17] = minimumFreq */
  0,   /* field[0] = power */
  3,   /* field[3] = pressureDiffSta */
  19,   /* field[19] = targetCo2 */
  12,   /* field[12] = targetHumidity */
  15,   /* field[15] = targetPres1 */
  16,   /* field[16] = targetPres2 */
  10,   /* field[10] = targetTemperature */
  5,   /* field[5] = vlvFeedback */
  4,   /* field[4] = vlvOpening */
};
static const ProtobufCIntRange iot__service__sf__properties__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 20 }
};
const ProtobufCMessageDescriptor iot__service__sf__properties__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.sf.Properties",
  "Properties",
  "Iot__Service__Sf__Properties",
  "iot.service.sf",
  sizeof(Iot__Service__Sf__Properties),
  20,
  iot__service__sf__properties__field_descriptors,
  iot__service__sf__properties__field_indices_by_name,
  1,  iot__service__sf__properties__number_ranges,
  (ProtobufCMessageInit) iot__service__sf__properties__init,
  NULL,NULL,NULL    /* reserved[123] */
};
