/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cloudMedia.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cloudMedia.pb-c.h"
void   iot__service__cloud_media__action_in_one_touch_call__init
                     (Iot__Service__CloudMedia__ActionInOneTouchCall         *message)
{
  static const Iot__Service__CloudMedia__ActionInOneTouchCall init_value = IOT__SERVICE__CLOUD_MEDIA__ACTION_IN_ONE_TOUCH_CALL__INIT;
  *message = init_value;
}
size_t iot__service__cloud_media__action_in_one_touch_call__get_packed_size
                     (const Iot__Service__CloudMedia__ActionInOneTouchCall *message)
{
  assert(message->base.descriptor == &iot__service__cloud_media__action_in_one_touch_call__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__cloud_media__action_in_one_touch_call__pack
                     (const Iot__Service__CloudMedia__ActionInOneTouchCall *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__cloud_media__action_in_one_touch_call__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__cloud_media__action_in_one_touch_call__pack_to_buffer
                     (const Iot__Service__CloudMedia__ActionInOneTouchCall *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__cloud_media__action_in_one_touch_call__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__CloudMedia__ActionInOneTouchCall *
       iot__service__cloud_media__action_in_one_touch_call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__CloudMedia__ActionInOneTouchCall *)
     protobuf_c_message_unpack (&iot__service__cloud_media__action_in_one_touch_call__descriptor,
                                allocator, len, data);
}
void   iot__service__cloud_media__action_in_one_touch_call__free_unpacked
                     (Iot__Service__CloudMedia__ActionInOneTouchCall *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__cloud_media__action_in_one_touch_call__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot__service__cloud_media__action_out_one_touch_call__init
                     (Iot__Service__CloudMedia__ActionOutOneTouchCall         *message)
{
  static const Iot__Service__CloudMedia__ActionOutOneTouchCall init_value = IOT__SERVICE__CLOUD_MEDIA__ACTION_OUT_ONE_TOUCH_CALL__INIT;
  *message = init_value;
}
size_t iot__service__cloud_media__action_out_one_touch_call__get_packed_size
                     (const Iot__Service__CloudMedia__ActionOutOneTouchCall *message)
{
  assert(message->base.descriptor == &iot__service__cloud_media__action_out_one_touch_call__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__cloud_media__action_out_one_touch_call__pack
                     (const Iot__Service__CloudMedia__ActionOutOneTouchCall *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__cloud_media__action_out_one_touch_call__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__cloud_media__action_out_one_touch_call__pack_to_buffer
                     (const Iot__Service__CloudMedia__ActionOutOneTouchCall *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__cloud_media__action_out_one_touch_call__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__CloudMedia__ActionOutOneTouchCall *
       iot__service__cloud_media__action_out_one_touch_call__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__CloudMedia__ActionOutOneTouchCall *)
     protobuf_c_message_unpack (&iot__service__cloud_media__action_out_one_touch_call__descriptor,
                                allocator, len, data);
}
void   iot__service__cloud_media__action_out_one_touch_call__free_unpacked
                     (Iot__Service__CloudMedia__ActionOutOneTouchCall *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__cloud_media__action_out_one_touch_call__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot__service__cloud_media__properties__init
                     (Iot__Service__CloudMedia__Properties         *message)
{
  static const Iot__Service__CloudMedia__Properties init_value = IOT__SERVICE__CLOUD_MEDIA__PROPERTIES__INIT;
  *message = init_value;
}
size_t iot__service__cloud_media__properties__get_packed_size
                     (const Iot__Service__CloudMedia__Properties *message)
{
  assert(message->base.descriptor == &iot__service__cloud_media__properties__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__cloud_media__properties__pack
                     (const Iot__Service__CloudMedia__Properties *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__cloud_media__properties__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__cloud_media__properties__pack_to_buffer
                     (const Iot__Service__CloudMedia__Properties *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__cloud_media__properties__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__CloudMedia__Properties *
       iot__service__cloud_media__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__CloudMedia__Properties *)
     protobuf_c_message_unpack (&iot__service__cloud_media__properties__descriptor,
                                allocator, len, data);
}
void   iot__service__cloud_media__properties__free_unpacked
                     (Iot__Service__CloudMedia__Properties *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__cloud_media__properties__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor iot__service__cloud_media__action_in_one_touch_call__field_descriptors[2] =
{
  {
    "timeout",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__CloudMedia__ActionInOneTouchCall, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eventUuid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__CloudMedia__ActionInOneTouchCall, eventuuid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot__service__cloud_media__action_in_one_touch_call__field_indices_by_name[] = {
  1,   /* field[1] = eventUuid */
  0,   /* field[0] = timeout */
};
static const ProtobufCIntRange iot__service__cloud_media__action_in_one_touch_call__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor iot__service__cloud_media__action_in_one_touch_call__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.cloudMedia.ActionInOneTouchCall",
  "ActionInOneTouchCall",
  "Iot__Service__CloudMedia__ActionInOneTouchCall",
  "iot.service.cloudMedia",
  sizeof(Iot__Service__CloudMedia__ActionInOneTouchCall),
  2,
  iot__service__cloud_media__action_in_one_touch_call__field_descriptors,
  iot__service__cloud_media__action_in_one_touch_call__field_indices_by_name,
  1,  iot__service__cloud_media__action_in_one_touch_call__number_ranges,
  (ProtobufCMessageInit) iot__service__cloud_media__action_in_one_touch_call__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue iot__service__cloud_media__action_out_one_touch_call__code__enum_values_by_number[5] =
{
  { "SUCCESS", "IOT__SERVICE__CLOUD_MEDIA__ACTION_OUT_ONE_TOUCH_CALL__CODE__SUCCESS", 0 },
  { "NOT_CONFIGURED", "IOT__SERVICE__CLOUD_MEDIA__ACTION_OUT_ONE_TOUCH_CALL__CODE__NOT_CONFIGURED", 1 },
  { "TIMEOUT_NO_ANSWER", "IOT__SERVICE__CLOUD_MEDIA__ACTION_OUT_ONE_TOUCH_CALL__CODE__TIMEOUT_NO_ANSWER", 2 },
  { "REFUSE", "IOT__SERVICE__CLOUD_MEDIA__ACTION_OUT_ONE_TOUCH_CALL__CODE__REFUSE", 3 },
  { "BUSY", "IOT__SERVICE__CLOUD_MEDIA__ACTION_OUT_ONE_TOUCH_CALL__CODE__BUSY", 4 },
};
static const ProtobufCIntRange iot__service__cloud_media__action_out_one_touch_call__code__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex iot__service__cloud_media__action_out_one_touch_call__code__enum_values_by_name[5] =
{
  { "BUSY", 4 },
  { "NOT_CONFIGURED", 1 },
  { "REFUSE", 3 },
  { "SUCCESS", 0 },
  { "TIMEOUT_NO_ANSWER", 2 },
};
const ProtobufCEnumDescriptor iot__service__cloud_media__action_out_one_touch_call__code__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "iot.service.cloudMedia.ActionOutOneTouchCall.Code",
  "Code",
  "Iot__Service__CloudMedia__ActionOutOneTouchCall__Code",
  "iot.service.cloudMedia",
  5,
  iot__service__cloud_media__action_out_one_touch_call__code__enum_values_by_number,
  5,
  iot__service__cloud_media__action_out_one_touch_call__code__enum_values_by_name,
  1,
  iot__service__cloud_media__action_out_one_touch_call__code__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor iot__service__cloud_media__action_out_one_touch_call__field_descriptors[1] =
{
  {
    "code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__CloudMedia__ActionOutOneTouchCall, code),
    &iot__service__cloud_media__action_out_one_touch_call__code__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot__service__cloud_media__action_out_one_touch_call__field_indices_by_name[] = {
  0,   /* field[0] = code */
};
static const ProtobufCIntRange iot__service__cloud_media__action_out_one_touch_call__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor iot__service__cloud_media__action_out_one_touch_call__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.cloudMedia.ActionOutOneTouchCall",
  "ActionOutOneTouchCall",
  "Iot__Service__CloudMedia__ActionOutOneTouchCall",
  "iot.service.cloudMedia",
  sizeof(Iot__Service__CloudMedia__ActionOutOneTouchCall),
  1,
  iot__service__cloud_media__action_out_one_touch_call__field_descriptors,
  iot__service__cloud_media__action_out_one_touch_call__field_indices_by_name,
  1,  iot__service__cloud_media__action_out_one_touch_call__number_ranges,
  (ProtobufCMessageInit) iot__service__cloud_media__action_out_one_touch_call__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define iot__service__cloud_media__properties__field_descriptors NULL
#define iot__service__cloud_media__properties__field_indices_by_name NULL
#define iot__service__cloud_media__properties__number_ranges NULL
const ProtobufCMessageDescriptor iot__service__cloud_media__properties__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.cloudMedia.Properties",
  "Properties",
  "Iot__Service__CloudMedia__Properties",
  "iot.service.cloudMedia",
  sizeof(Iot__Service__CloudMedia__Properties),
  0,
  iot__service__cloud_media__properties__field_descriptors,
  iot__service__cloud_media__properties__field_indices_by_name,
  0,  iot__service__cloud_media__properties__number_ranges,
  (ProtobufCMessageInit) iot__service__cloud_media__properties__init,
  NULL,NULL,NULL    /* reserved[123] */
};
