/* Generated by the heythings model compiler.  DO NOT EDIT! */
/* Generated from: refrigerator.proto */

#include <errno.h>
#include <assert.h>
#include "refrigerator.pb-c.h"
#include "refrigerator_service.h"
#include "hey/schema.h"

#define REFRIGERATOR_SERVICE (59 * 256)
#define PROP_IID_CNT 21

static const struct hey_schema_property refrigerator_properties_iids[] = {
    [0] = { .iid = 1, .type = HEY_PROPERTY_TYPE_GENERIC },
    [1] = { .iid = 2, .type = HEY_PROPERTY_TYPE_GENERIC },
    [2] = { .iid = 3, .type = HEY_PROPERTY_TYPE_GENERIC },
    [3] = { .iid = 4, .type = HEY_PROPERTY_TYPE_GENERIC },
    [4] = { .iid = 5, .type = HEY_PROPERTY_TYPE_GENERIC },
    [5] = { .iid = 6, .type = HEY_PROPERTY_TYPE_GENERIC },
    [6] = { .iid = 7, .type = HEY_PROPERTY_TYPE_GENERIC },
    [7] = { .iid = 8, .type = HEY_PROPERTY_TYPE_GENERIC },
    [8] = { .iid = 9, .type = HEY_PROPERTY_TYPE_GENERIC },
    [9] = { .iid = 10, .type = HEY_PROPERTY_TYPE_GENERIC },
    [10] = { .iid = 11, .type = HEY_PROPERTY_TYPE_GENERIC },
    [11] = { .iid = 12, .type = HEY_PROPERTY_TYPE_GENERIC },
    [12] = { .iid = 13, .type = HEY_PROPERTY_TYPE_GENERIC },
    [13] = { .iid = 14, .type = HEY_PROPERTY_TYPE_GENERIC },
    [14] = { .iid = 15, .type = HEY_PROPERTY_TYPE_GENERIC },
    [15] = { .iid = 16, .type = HEY_PROPERTY_TYPE_GENERIC },
    [16] = { .iid = 17, .type = HEY_PROPERTY_TYPE_GENERIC },
    [17] = { .iid = 18, .type = HEY_PROPERTY_TYPE_GENERIC },
    [18] = { .iid = 19, .type = HEY_PROPERTY_TYPE_GENERIC },
    [19] = { .iid = 20, .type = HEY_PROPERTY_TYPE_GENERIC },
    [20] = { .iid = 21, .type = HEY_PROPERTY_TYPE_GENERIC },
};
static struct hey_service *refrigerator_service;

static int32_t service_refrigerator_properties_write_cb(void *cb_data, size_t n_iid, uint32_t *iids,
                                                        size_t len, uint8_t *value)
{
    Iot__Service__Refrigerator__Properties *props = iot__service__refrigerator__properties__unpack(NULL, len, value);
    if (NULL == props) {
        return EINVAL;
    }

    int32_t ret = 0;
    struct refrigerator_properties properties = { 0 };
    properties.power = props->power;
    properties.devlable = props->devlable;
    properties.refrigeratorlevel = props->refrigeratorlevel;
    properties.currenttemperature = props->currenttemperature;
    properties.targettemperature = props->targettemperature;
    properties.quickrefrigeratingmode = props->quickrefrigeratingmode;
    properties.highhumiditymode = props->highhumiditymode;
    properties.lightwavepreservationmode = props->lightwavepreservationmode;
    properties.radarmodeenabled = props->radarmodeenabled;
    properties.sterilizationenabled = props->sterilizationenabled;
    properties.superfreshnessenabled = props->superfreshnessenabled;
    properties.odorlessnessenabled = props->odorlessnessenabled;
    properties.cleanfruitenabled = props->cleanfruitenabled;
    properties.colmocleanfruit = props->colmocleanfruit;
    properties.efficientsterilization = props->efficientsterilization;
    properties.humiditycontrolenabled = props->humiditycontrolenabled;
    properties.sfcompartmentpower = props->sfcompartmentpower;
    properties.sfcompartmenttemp = props->sfcompartmenttemp;
    properties.sfcompartmentcurrenttemp = props->sfcompartmentcurrenttemp;
    properties.tcompartmentpower = props->tcompartmentpower;
    properties.wscompartmentpower = props->wscompartmentpower;
    ret = refrigerator_properties_write_cb(n_iid, iids, &properties);

    iot__service__refrigerator__properties__free_unpacked(props, NULL);
    return ret;
}

static const struct hey_properties_callbacks props_cbs = {
    .write = service_refrigerator_properties_write_cb
};

static int refrigerator_service_register(Iot__Service__Refrigerator__Properties *props)
{
    uint8_t *buf;
    size_t buf_len;
    buf_len = iot__service__refrigerator__properties__get_packed_size(props);
    if (buf_len == 0) {
        buf = NULL;
    } else {
        buf = malloc(buf_len);
        if (!buf) {
            return ENOMEM;
        }
        iot__service__refrigerator__properties__pack(props, buf);
    }

    struct hey_schema_service schema_srv;
    hey_schema_service_init(&schema_srv);
    schema_srv.properties.iids = (struct hey_schema_property *)refrigerator_properties_iids;
    schema_srv.properties.n_iid = PROP_IID_CNT;
    schema_srv.properties.value = buf;
    schema_srv.properties.len = buf_len;
    schema_srv.properties.cbs = &props_cbs;
    refrigerator_service = hey_service_register(REFRIGERATOR_SERVICE, &schema_srv, NULL);
    if (NULL == refrigerator_service) {
        free(buf);
        return errno;
    }

    free(buf);
    return 0;
}

/**
 * @brief update properties of refrigerator service
 * @param count      [the number of properties to be updated]
 * @param enumerate  [the iid enumeration of properties to be updated]
 * @param properties [properties structure with updated content]
 * @return int32_t   [update result]
 */
int32_t refrigerator_properties_update(size_t count, uint32_t *enumerate, struct refrigerator_properties *properties)
{
    assert(count <= PROP_IID_CNT);
    if (NULL == properties) {
        return EINVAL;
    }

    int ret = 0;
    Iot__Service__Refrigerator__Properties *props = NULL;
    uint8_t *buf = NULL;
    props = malloc(sizeof(Iot__Service__Refrigerator__Properties));
    if (NULL == props) {
        ret = ENOMEM;
        goto out;
    }
    iot__service__refrigerator__properties__init(props);
    props->power = properties->power;
    props->devlable = properties->devlable;
    props->refrigeratorlevel = properties->refrigeratorlevel;
    props->currenttemperature = properties->currenttemperature;
    props->targettemperature = properties->targettemperature;
    props->quickrefrigeratingmode = properties->quickrefrigeratingmode;
    props->highhumiditymode = properties->highhumiditymode;
    props->lightwavepreservationmode = properties->lightwavepreservationmode;
    props->radarmodeenabled = properties->radarmodeenabled;
    props->sterilizationenabled = properties->sterilizationenabled;
    props->superfreshnessenabled = properties->superfreshnessenabled;
    props->odorlessnessenabled = properties->odorlessnessenabled;
    props->cleanfruitenabled = properties->cleanfruitenabled;
    props->colmocleanfruit = properties->colmocleanfruit;
    props->efficientsterilization = properties->efficientsterilization;
    props->humiditycontrolenabled = properties->humiditycontrolenabled;
    props->sfcompartmentpower = properties->sfcompartmentpower;
    props->sfcompartmenttemp = properties->sfcompartmenttemp;
    props->sfcompartmentcurrenttemp = properties->sfcompartmentcurrenttemp;
    props->tcompartmentpower = properties->tcompartmentpower;
    props->wscompartmentpower = properties->wscompartmentpower;

    size_t buf_len;
    buf_len = iot__service__refrigerator__properties__get_packed_size(props);
    if (buf_len > 0) {
        buf = malloc(buf_len);
        if (NULL == buf) {
            ret = ENOMEM;
            goto out;
        }
        iot__service__refrigerator__properties__pack(props, buf);
    }

    struct hey_properties_content content = {
        .n_iid = count,
        .iids = enumerate,
        .len = buf_len,
        .value = buf
    };
    ret = hey_properties_update(refrigerator_service, &content);

out:
    free(props);
    free(buf);
    return ret;
}

/**
 * @brief refrigerator service initialization
 * @param properties [refrigerator service properties]
 * @return int32_t   [initialize result]
*/
int32_t refrigerator_service_init(const struct refrigerator_properties *properties)
{
    int ret = 0;
    Iot__Service__Refrigerator__Properties *props = NULL;
    props = malloc(sizeof(Iot__Service__Refrigerator__Properties));
    if (NULL == props) {
        ret = ENOMEM;
        goto out;
    }
    iot__service__refrigerator__properties__init(props);
    if (NULL != properties) {
        props->power = properties->power;
        props->devlable = properties->devlable;
        props->refrigeratorlevel = properties->refrigeratorlevel;
        props->currenttemperature = properties->currenttemperature;
        props->targettemperature = properties->targettemperature;
        props->quickrefrigeratingmode = properties->quickrefrigeratingmode;
        props->highhumiditymode = properties->highhumiditymode;
        props->lightwavepreservationmode = properties->lightwavepreservationmode;
        props->radarmodeenabled = properties->radarmodeenabled;
        props->sterilizationenabled = properties->sterilizationenabled;
        props->superfreshnessenabled = properties->superfreshnessenabled;
        props->odorlessnessenabled = properties->odorlessnessenabled;
        props->cleanfruitenabled = properties->cleanfruitenabled;
        props->colmocleanfruit = properties->colmocleanfruit;
        props->efficientsterilization = properties->efficientsterilization;
        props->humiditycontrolenabled = properties->humiditycontrolenabled;
        props->sfcompartmentpower = properties->sfcompartmentpower;
        props->sfcompartmenttemp = properties->sfcompartmenttemp;
        props->sfcompartmentcurrenttemp = properties->sfcompartmentcurrenttemp;
        props->tcompartmentpower = properties->tcompartmentpower;
        props->wscompartmentpower = properties->wscompartmentpower;
    }

    ret = refrigerator_service_register(props);

out:
    free(props);
    return ret;
}
