/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cloudSubDeviceBind.proto */

#ifndef PROTOBUF_C_cloudSubDeviceBind_2eproto__INCLUDED
#define PROTOBUF_C_cloudSubDeviceBind_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType;
typedef struct _Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType;
typedef struct _Iot__Service__CloudSubDeviceBind__Properties Iot__Service__CloudSubDeviceBind__Properties;


/* --- enums --- */

typedef enum _Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType__SetupType {
  IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_SUB_DEVICE_GET_SETUP_TYPE__SETUP_TYPE__ECDH = 0,
  IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_SUB_DEVICE_GET_SETUP_TYPE__SETUP_TYPE__ECJPAKE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_SUB_DEVICE_GET_SETUP_TYPE__SETUP_TYPE)
} Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType__SetupType;

/* --- messages --- */

struct  _Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind
{
  ProtobufCMessage base;
  /*
   *当此字段为空时子设备绑定的用户和家庭与网关一致
   */
  ProtobufCBinaryData bindkey;
  char *pid;
  /*
   *一型一密设备唯一标识，such as mac or sn，需提前上传到HeyThings平台，平台需验证其是否已录入及与pid是否匹配
   */
  char *vendordevid;
  /*
   *设备公钥，用于上传云端进行域签名，以及用来验证设备的唯一性（非首次绑定时需要验证其与vendorDevId或did对应的首次绑定时的devPubKey是否一致，若不一致拒绝绑定），设备首次生成后永久保存不再更改
   */
  ProtobufCBinaryData devpubkey;
  /*
   *一机一密设备唯一标识，HeyThings平台生成并预置到设备中，平台需验证其是否已存在及与pid是否匹配
   */
  char *did;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_IN_SUB_DEVICE_BIND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_in_sub_device_bind__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string }


struct  _Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind
{
  ProtobufCMessage base;
  uint32_t devaddress;
  ProtobufCBinaryData domaincert;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_SUB_DEVICE_BIND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_out_sub_device_bind__descriptor) \
    , 0, {0,NULL} }


struct  _Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind
{
  ProtobufCMessage base;
  /*
   *当此字段为空时子设备绑定的用户和家庭与网关一致
   */
  ProtobufCBinaryData bindkey;
  char *pid;
  /*
   *一型一密设备唯一标识，such as mac or sn，需提前上传到HeyThings平台，平台需验证其是否已录入及与pid是否匹配
   */
  char *vendordevid;
  /*
   *设备公钥，用于上传云端进行域签名，以及用来验证设备的唯一性（非首次绑定时需要验证其与vendorDevId或did对应的首次绑定时的devPubKey是否一致，若不一致拒绝绑定），设备首次生成后永久保存不再更改
   */
  ProtobufCBinaryData devpubkey;
  /*
   *一机一密设备唯一标识，HeyThings平台生成并预置到设备中，平台需验证其是否已存在及与pid是否匹配
   */
  char *did;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_IN_BLE_SUB_DEVICE_BIND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, {0,NULL}, (char *)protobuf_c_empty_string }


struct  _Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind
{
  ProtobufCMessage base;
  /*
   *地址高两字节固定为0x0102
   */
  uint32_t devaddress;
  ProtobufCBinaryData domaincert;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_SUB_DEVICE_BIND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__descriptor) \
    , 0, {0,NULL} }


struct  _Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind
{
  ProtobufCMessage base;
  ProtobufCBinaryData bindkey;
  char *uuid;
  /*
   *地址高两字节固定为0x0101
   */
  uint32_t devaddress;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_IN_BLE_MESH_SUB_DEVICE_BIND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__descriptor) \
    , {0,NULL}, (char *)protobuf_c_empty_string, 0 }


struct  _Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_MESH_SUB_DEVICE_BIND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__descriptor) \
     }


struct  _Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob
{
  ProtobufCMessage base;
  char *uuid;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_IN_BLE_MESH_GET_OOB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob
{
  ProtobufCMessage base;
  ProtobufCBinaryData oob;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_MESH_GET_OOB__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__descriptor) \
    , {0,NULL} }


struct  _Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType
{
  ProtobufCMessage base;
  char *pid;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_IN_BLE_SUB_DEVICE_GET_SETUP_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType
{
  ProtobufCMessage base;
  Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType__SetupType type;
  ProtobufCBinaryData ecdhpubkey;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_SUB_DEVICE_GET_SETUP_TYPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__descriptor) \
    , IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__ACTION_OUT_BLE_SUB_DEVICE_GET_SETUP_TYPE__SETUP_TYPE__ECDH, {0,NULL} }


struct  _Iot__Service__CloudSubDeviceBind__Properties
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__CLOUD_SUB_DEVICE_BIND__PROPERTIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__cloud_sub_device_bind__properties__descriptor) \
     }


/* Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind methods */
void   iot__service__cloud_sub_device_bind__action_in_sub_device_bind__init
                     (Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind         *message);
size_t iot__service__cloud_sub_device_bind__action_in_sub_device_bind__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind   *message);
size_t iot__service__cloud_sub_device_bind__action_in_sub_device_bind__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_in_sub_device_bind__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind *
       iot__service__cloud_sub_device_bind__action_in_sub_device_bind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_in_sub_device_bind__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind methods */
void   iot__service__cloud_sub_device_bind__action_out_sub_device_bind__init
                     (Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind         *message);
size_t iot__service__cloud_sub_device_bind__action_out_sub_device_bind__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind   *message);
size_t iot__service__cloud_sub_device_bind__action_out_sub_device_bind__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_out_sub_device_bind__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind *
       iot__service__cloud_sub_device_bind__action_out_sub_device_bind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_out_sub_device_bind__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind methods */
void   iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__init
                     (Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind         *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind   *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind *
       iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind methods */
void   iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__init
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind         *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind   *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind *
       iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind methods */
void   iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__init
                     (Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind         *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind   *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind *
       iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind methods */
void   iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__init
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind         *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind   *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind *
       iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob methods */
void   iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__init
                     (Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob         *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob   *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob *
       iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob methods */
void   iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__init
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob         *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob   *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob *
       iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType methods */
void   iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__init
                     (Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType         *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType   *message);
size_t iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType *
       iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType methods */
void   iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__init
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType         *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType   *message);
size_t iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__pack
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType *
       iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__CloudSubDeviceBind__Properties methods */
void   iot__service__cloud_sub_device_bind__properties__init
                     (Iot__Service__CloudSubDeviceBind__Properties         *message);
size_t iot__service__cloud_sub_device_bind__properties__get_packed_size
                     (const Iot__Service__CloudSubDeviceBind__Properties   *message);
size_t iot__service__cloud_sub_device_bind__properties__pack
                     (const Iot__Service__CloudSubDeviceBind__Properties   *message,
                      uint8_t             *out);
size_t iot__service__cloud_sub_device_bind__properties__pack_to_buffer
                     (const Iot__Service__CloudSubDeviceBind__Properties   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__CloudSubDeviceBind__Properties *
       iot__service__cloud_sub_device_bind__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__cloud_sub_device_bind__properties__free_unpacked
                     (Iot__Service__CloudSubDeviceBind__Properties *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionInSubDeviceBind *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionOutSubDeviceBind *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceBind *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceBind *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshSubDeviceBind *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshSubDeviceBind *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionInBleMeshGetOob *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionOutBleMeshGetOob *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionInBleSubDeviceGetSetupType *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType_Closure)
                 (const Iot__Service__CloudSubDeviceBind__ActionOutBleSubDeviceGetSetupType *message,
                  void *closure_data);
typedef void (*Iot__Service__CloudSubDeviceBind__Properties_Closure)
                 (const Iot__Service__CloudSubDeviceBind__Properties *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_in_sub_device_bind__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_out_sub_device_bind__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_in_ble_sub_device_bind__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_out_ble_sub_device_bind__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_in_ble_mesh_sub_device_bind__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_out_ble_mesh_sub_device_bind__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_in_ble_mesh_get_oob__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_out_ble_mesh_get_oob__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_in_ble_sub_device_get_setup_type__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__cloud_sub_device_bind__action_out_ble_sub_device_get_setup_type__setup_type__descriptor;
extern const ProtobufCMessageDescriptor iot__service__cloud_sub_device_bind__properties__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cloudSubDeviceBind_2eproto__INCLUDED */
