/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: steamOven.proto */

#ifndef PROTOBUF_C_steamOven_2eproto__INCLUDED
#define PROTOBUF_C_steamOven_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Iot__Service__SteamOven__AppointmentTaskCompleted Iot__Service__SteamOven__AppointmentTaskCompleted;
typedef struct _Iot__Service__SteamOven__EventOpenAlarm Iot__Service__SteamOven__EventOpenAlarm;
typedef struct _Iot__Service__SteamOven__Properties Iot__Service__SteamOven__Properties;


/* --- enums --- */

typedef enum _Iot__Service__SteamOven__OperationMode {
  IOT__SERVICE__STEAM_OVEN__OPERATION_MODE__STOP = 0,
  IOT__SERVICE__STEAM_OVEN__OPERATION_MODE__PAUSE = 1,
  IOT__SERVICE__STEAM_OVEN__OPERATION_MODE__RESUME = 2,
  IOT__SERVICE__STEAM_OVEN__OPERATION_MODE__CANCEL = 3,
  IOT__SERVICE__STEAM_OVEN__OPERATION_MODE__START = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__STEAM_OVEN__OPERATION_MODE)
} Iot__Service__SteamOven__OperationMode;
typedef enum _Iot__Service__SteamOven__MachineStatus {
  IOT__SERVICE__STEAM_OVEN__MACHINE_STATUS__IDLE = 0,
  IOT__SERVICE__STEAM_OVEN__MACHINE_STATUS__PREACTIVE = 1,
  IOT__SERVICE__STEAM_OVEN__MACHINE_STATUS__ACTIVE = 2,
  IOT__SERVICE__STEAM_OVEN__MACHINE_STATUS__STOPED = 3,
  IOT__SERVICE__STEAM_OVEN__MACHINE_STATUS__ERROR = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__STEAM_OVEN__MACHINE_STATUS)
} Iot__Service__SteamOven__MachineStatus;
typedef enum _Iot__Service__SteamOven__OvenMode {
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__MANUAL = 0,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__MEAT_VEGETABLE = 1,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__BAKE = 2,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__PIZZA = 3,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__ROTATION = 4,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__AIR_DRY = 5,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__FERMENTATION = 6,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__HOT_WIND = 7,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__AIR_FRY = 8,
  IOT__SERVICE__STEAM_OVEN__OVEN_MODE__UNFREEZE = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__STEAM_OVEN__OVEN_MODE)
} Iot__Service__SteamOven__OvenMode;
typedef enum _Iot__Service__SteamOven__PreheatStatus {
  IOT__SERVICE__STEAM_OVEN__PREHEAT_STATUS__PREHEAT_NONE = 0,
  IOT__SERVICE__STEAM_OVEN__PREHEAT_STATUS__PREHEATING = 1,
  IOT__SERVICE__STEAM_OVEN__PREHEAT_STATUS__PREHEAT_END = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__STEAM_OVEN__PREHEAT_STATUS)
} Iot__Service__SteamOven__PreheatStatus;
typedef enum _Iot__Service__SteamOven__OvenWorkMode {
  IOT__SERVICE__STEAM_OVEN__OVEN_WORK_MODE__STEAM = 0,
  IOT__SERVICE__STEAM_OVEN__OVEN_WORK_MODE__ROAST = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__STEAM_OVEN__OVEN_WORK_MODE)
} Iot__Service__SteamOven__OvenWorkMode;
typedef enum _Iot__Service__SteamOven__JobStatus {
  IOT__SERVICE__STEAM_OVEN__JOB_STATUS__STANDBY_STATUS = 0,
  IOT__SERVICE__STEAM_OVEN__JOB_STATUS__PREACTIVE_STATUS = 1,
  IOT__SERVICE__STEAM_OVEN__JOB_STATUS__WORK_STATUS = 2,
  IOT__SERVICE__STEAM_OVEN__JOB_STATUS__PAUSE_STATUS = 3,
  IOT__SERVICE__STEAM_OVEN__JOB_STATUS__CANCEL_STATUS = 4,
  IOT__SERVICE__STEAM_OVEN__JOB_STATUS__COMPLETE_STATUS = 5
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__STEAM_OVEN__JOB_STATUS)
} Iot__Service__SteamOven__JobStatus;

/* --- messages --- */

struct  _Iot__Service__SteamOven__AppointmentTaskCompleted
{
  ProtobufCMessage base;
  protobuf_c_boolean status;
  char *name;
  uint32_t hour;
  uint32_t min;
  uint32_t sec;
};
#define IOT__SERVICE__STEAM_OVEN__APPOINTMENT_TASK_COMPLETED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__steam_oven__appointment_task_completed__descriptor) \
    , 0, (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  _Iot__Service__SteamOven__EventOpenAlarm
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__STEAM_OVEN__EVENT_OPEN_ALARM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__steam_oven__event_open_alarm__descriptor) \
     }


struct  _Iot__Service__SteamOven__Properties
{
  ProtobufCMessage base;
  protobuf_c_boolean power;
  Iot__Service__SteamOven__OperationMode operationmode;
  uint32_t operationtime;
  int32_t currenttemperature;
  int32_t targettemperature;
  Iot__Service__SteamOven__OvenMode ovenmode;
  protobuf_c_boolean preheatenabled;
  Iot__Service__SteamOven__PreheatStatus preheatstatus;
  Iot__Service__SteamOven__OvenWorkMode ovenworkmode;
  Iot__Service__SteamOven__AppointmentTaskCompleted *appointmenttaskcompleted;
  Iot__Service__SteamOven__JobStatus jobstatus;
  uint32_t remaintime;
  /*
   * event openAlarm(EventOpenAlarm) = 14;
   */
  Iot__Service__SteamOven__MachineStatus machinestatus;
};
#define IOT__SERVICE__STEAM_OVEN__PROPERTIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__steam_oven__properties__descriptor) \
    , 0, IOT__SERVICE__STEAM_OVEN__OPERATION_MODE__STOP, 0, 0, 0, IOT__SERVICE__STEAM_OVEN__OVEN_MODE__MANUAL, 0, IOT__SERVICE__STEAM_OVEN__PREHEAT_STATUS__PREHEAT_NONE, IOT__SERVICE__STEAM_OVEN__OVEN_WORK_MODE__STEAM, NULL, IOT__SERVICE__STEAM_OVEN__JOB_STATUS__STANDBY_STATUS, 0, IOT__SERVICE__STEAM_OVEN__MACHINE_STATUS__IDLE }


/* Iot__Service__SteamOven__AppointmentTaskCompleted methods */
void   iot__service__steam_oven__appointment_task_completed__init
                     (Iot__Service__SteamOven__AppointmentTaskCompleted         *message);
size_t iot__service__steam_oven__appointment_task_completed__get_packed_size
                     (const Iot__Service__SteamOven__AppointmentTaskCompleted   *message);
size_t iot__service__steam_oven__appointment_task_completed__pack
                     (const Iot__Service__SteamOven__AppointmentTaskCompleted   *message,
                      uint8_t             *out);
size_t iot__service__steam_oven__appointment_task_completed__pack_to_buffer
                     (const Iot__Service__SteamOven__AppointmentTaskCompleted   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__SteamOven__AppointmentTaskCompleted *
       iot__service__steam_oven__appointment_task_completed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__steam_oven__appointment_task_completed__free_unpacked
                     (Iot__Service__SteamOven__AppointmentTaskCompleted *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__SteamOven__EventOpenAlarm methods */
void   iot__service__steam_oven__event_open_alarm__init
                     (Iot__Service__SteamOven__EventOpenAlarm         *message);
size_t iot__service__steam_oven__event_open_alarm__get_packed_size
                     (const Iot__Service__SteamOven__EventOpenAlarm   *message);
size_t iot__service__steam_oven__event_open_alarm__pack
                     (const Iot__Service__SteamOven__EventOpenAlarm   *message,
                      uint8_t             *out);
size_t iot__service__steam_oven__event_open_alarm__pack_to_buffer
                     (const Iot__Service__SteamOven__EventOpenAlarm   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__SteamOven__EventOpenAlarm *
       iot__service__steam_oven__event_open_alarm__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__steam_oven__event_open_alarm__free_unpacked
                     (Iot__Service__SteamOven__EventOpenAlarm *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__SteamOven__Properties methods */
void   iot__service__steam_oven__properties__init
                     (Iot__Service__SteamOven__Properties         *message);
size_t iot__service__steam_oven__properties__get_packed_size
                     (const Iot__Service__SteamOven__Properties   *message);
size_t iot__service__steam_oven__properties__pack
                     (const Iot__Service__SteamOven__Properties   *message,
                      uint8_t             *out);
size_t iot__service__steam_oven__properties__pack_to_buffer
                     (const Iot__Service__SteamOven__Properties   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__SteamOven__Properties *
       iot__service__steam_oven__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__steam_oven__properties__free_unpacked
                     (Iot__Service__SteamOven__Properties *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Iot__Service__SteamOven__AppointmentTaskCompleted_Closure)
                 (const Iot__Service__SteamOven__AppointmentTaskCompleted *message,
                  void *closure_data);
typedef void (*Iot__Service__SteamOven__EventOpenAlarm_Closure)
                 (const Iot__Service__SteamOven__EventOpenAlarm *message,
                  void *closure_data);
typedef void (*Iot__Service__SteamOven__Properties_Closure)
                 (const Iot__Service__SteamOven__Properties *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    iot__service__steam_oven__operation_mode__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__steam_oven__machine_status__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__steam_oven__oven_mode__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__steam_oven__preheat_status__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__steam_oven__oven_work_mode__descriptor;
extern const ProtobufCEnumDescriptor    iot__service__steam_oven__job_status__descriptor;
extern const ProtobufCMessageDescriptor iot__service__steam_oven__appointment_task_completed__descriptor;
extern const ProtobufCMessageDescriptor iot__service__steam_oven__event_open_alarm__descriptor;
extern const ProtobufCMessageDescriptor iot__service__steam_oven__properties__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_steamOven_2eproto__INCLUDED */
