/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gasCooker.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gasCooker.pb-c.h"
void   iot__service__gas_cooker__action_in_turn_off_fire__init
                     (Iot__Service__GasCooker__ActionInTurnOffFire         *message)
{
  static const Iot__Service__GasCooker__ActionInTurnOffFire init_value = IOT__SERVICE__GAS_COOKER__ACTION_IN_TURN_OFF_FIRE__INIT;
  *message = init_value;
}
size_t iot__service__gas_cooker__action_in_turn_off_fire__get_packed_size
                     (const Iot__Service__GasCooker__ActionInTurnOffFire *message)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__action_in_turn_off_fire__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__gas_cooker__action_in_turn_off_fire__pack
                     (const Iot__Service__GasCooker__ActionInTurnOffFire *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__action_in_turn_off_fire__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__gas_cooker__action_in_turn_off_fire__pack_to_buffer
                     (const Iot__Service__GasCooker__ActionInTurnOffFire *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__action_in_turn_off_fire__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__GasCooker__ActionInTurnOffFire *
       iot__service__gas_cooker__action_in_turn_off_fire__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__GasCooker__ActionInTurnOffFire *)
     protobuf_c_message_unpack (&iot__service__gas_cooker__action_in_turn_off_fire__descriptor,
                                allocator, len, data);
}
void   iot__service__gas_cooker__action_in_turn_off_fire__free_unpacked
                     (Iot__Service__GasCooker__ActionInTurnOffFire *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__gas_cooker__action_in_turn_off_fire__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot__service__gas_cooker__action_out_turn_off_fire__init
                     (Iot__Service__GasCooker__ActionOutTurnOffFire         *message)
{
  static const Iot__Service__GasCooker__ActionOutTurnOffFire init_value = IOT__SERVICE__GAS_COOKER__ACTION_OUT_TURN_OFF_FIRE__INIT;
  *message = init_value;
}
size_t iot__service__gas_cooker__action_out_turn_off_fire__get_packed_size
                     (const Iot__Service__GasCooker__ActionOutTurnOffFire *message)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__action_out_turn_off_fire__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__gas_cooker__action_out_turn_off_fire__pack
                     (const Iot__Service__GasCooker__ActionOutTurnOffFire *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__action_out_turn_off_fire__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__gas_cooker__action_out_turn_off_fire__pack_to_buffer
                     (const Iot__Service__GasCooker__ActionOutTurnOffFire *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__action_out_turn_off_fire__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__GasCooker__ActionOutTurnOffFire *
       iot__service__gas_cooker__action_out_turn_off_fire__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__GasCooker__ActionOutTurnOffFire *)
     protobuf_c_message_unpack (&iot__service__gas_cooker__action_out_turn_off_fire__descriptor,
                                allocator, len, data);
}
void   iot__service__gas_cooker__action_out_turn_off_fire__free_unpacked
                     (Iot__Service__GasCooker__ActionOutTurnOffFire *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__gas_cooker__action_out_turn_off_fire__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   iot__service__gas_cooker__properties__init
                     (Iot__Service__GasCooker__Properties         *message)
{
  static const Iot__Service__GasCooker__Properties init_value = IOT__SERVICE__GAS_COOKER__PROPERTIES__INIT;
  *message = init_value;
}
size_t iot__service__gas_cooker__properties__get_packed_size
                     (const Iot__Service__GasCooker__Properties *message)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__properties__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__gas_cooker__properties__pack
                     (const Iot__Service__GasCooker__Properties *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__properties__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__gas_cooker__properties__pack_to_buffer
                     (const Iot__Service__GasCooker__Properties *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__gas_cooker__properties__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__GasCooker__Properties *
       iot__service__gas_cooker__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__GasCooker__Properties *)
     protobuf_c_message_unpack (&iot__service__gas_cooker__properties__descriptor,
                                allocator, len, data);
}
void   iot__service__gas_cooker__properties__free_unpacked
                     (Iot__Service__GasCooker__Properties *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__gas_cooker__properties__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define iot__service__gas_cooker__action_in_turn_off_fire__field_descriptors NULL
#define iot__service__gas_cooker__action_in_turn_off_fire__field_indices_by_name NULL
#define iot__service__gas_cooker__action_in_turn_off_fire__number_ranges NULL
const ProtobufCMessageDescriptor iot__service__gas_cooker__action_in_turn_off_fire__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.gasCooker.ActionInTurnOffFire",
  "ActionInTurnOffFire",
  "Iot__Service__GasCooker__ActionInTurnOffFire",
  "iot.service.gasCooker",
  sizeof(Iot__Service__GasCooker__ActionInTurnOffFire),
  0,
  iot__service__gas_cooker__action_in_turn_off_fire__field_descriptors,
  iot__service__gas_cooker__action_in_turn_off_fire__field_indices_by_name,
  0,  iot__service__gas_cooker__action_in_turn_off_fire__number_ranges,
  (ProtobufCMessageInit) iot__service__gas_cooker__action_in_turn_off_fire__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define iot__service__gas_cooker__action_out_turn_off_fire__field_descriptors NULL
#define iot__service__gas_cooker__action_out_turn_off_fire__field_indices_by_name NULL
#define iot__service__gas_cooker__action_out_turn_off_fire__number_ranges NULL
const ProtobufCMessageDescriptor iot__service__gas_cooker__action_out_turn_off_fire__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.gasCooker.ActionOutTurnOffFire",
  "ActionOutTurnOffFire",
  "Iot__Service__GasCooker__ActionOutTurnOffFire",
  "iot.service.gasCooker",
  sizeof(Iot__Service__GasCooker__ActionOutTurnOffFire),
  0,
  iot__service__gas_cooker__action_out_turn_off_fire__field_descriptors,
  iot__service__gas_cooker__action_out_turn_off_fire__field_indices_by_name,
  0,  iot__service__gas_cooker__action_out_turn_off_fire__number_ranges,
  (ProtobufCMessageInit) iot__service__gas_cooker__action_out_turn_off_fire__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor iot__service__gas_cooker__properties__field_descriptors[1] =
{
  {
    "childLockEnabled",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__GasCooker__Properties, childlockenabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot__service__gas_cooker__properties__field_indices_by_name[] = {
  0,   /* field[0] = childLockEnabled */
};
static const ProtobufCIntRange iot__service__gas_cooker__properties__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor iot__service__gas_cooker__properties__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.gasCooker.Properties",
  "Properties",
  "Iot__Service__GasCooker__Properties",
  "iot.service.gasCooker",
  sizeof(Iot__Service__GasCooker__Properties),
  1,
  iot__service__gas_cooker__properties__field_descriptors,
  iot__service__gas_cooker__properties__field_indices_by_name,
  1,  iot__service__gas_cooker__properties__number_ranges,
  (ProtobufCMessageInit) iot__service__gas_cooker__properties__init,
  NULL,NULL,NULL    /* reserved[123] */
};
