/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: fileTransport.proto */

#ifndef PROTOBUF_C_fileTransport_2eproto__INCLUDED
#define PROTOBUF_C_fileTransport_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Iot__Service__FileTransport__ActionInFileUpload Iot__Service__FileTransport__ActionInFileUpload;
typedef struct _Iot__Service__FileTransport__ActionInFileUpload__FileInfo Iot__Service__FileTransport__ActionInFileUpload__FileInfo;
typedef struct _Iot__Service__FileTransport__ActionInFileUpload__Final Iot__Service__FileTransport__ActionInFileUpload__Final;
typedef struct _Iot__Service__FileTransport__ActionOutFileUpload Iot__Service__FileTransport__ActionOutFileUpload;
typedef struct _Iot__Service__FileTransport__ActionInFileDownload Iot__Service__FileTransport__ActionInFileDownload;
typedef struct _Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo;
typedef struct _Iot__Service__FileTransport__ActionOutFileDownload Iot__Service__FileTransport__ActionOutFileDownload;
typedef struct _Iot__Service__FileTransport__ActionOutFileDownload__FileInfo Iot__Service__FileTransport__ActionOutFileDownload__FileInfo;
typedef struct _Iot__Service__FileTransport__ActionOutFileDownload__Final Iot__Service__FileTransport__ActionOutFileDownload__Final;
typedef struct _Iot__Service__FileTransport__Properties Iot__Service__FileTransport__Properties;


/* --- enums --- */


/* --- messages --- */

struct  _Iot__Service__FileTransport__ActionInFileUpload__FileInfo
{
  ProtobufCMessage base;
  /*
   *文件名
   */
  char *name;
  /*
   *文件大小，单位：Byte，-1表示未知大小
   */
  int64_t size;
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__FILE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_in_file_upload__file_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _Iot__Service__FileTransport__ActionInFileUpload__Final
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__FINAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_in_file_upload__final__descriptor) \
     }


typedef enum {
  IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__SEND_TYPE__NOT_SET = 0,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__SEND_TYPE_FILE = 1,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__SEND_TYPE_CHUNK = 2,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__SEND_TYPE_FINAL = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__SEND_TYPE)
} Iot__Service__FileTransport__ActionInFileUpload__SendTypeCase;

struct  _Iot__Service__FileTransport__ActionInFileUpload
{
  ProtobufCMessage base;
  Iot__Service__FileTransport__ActionInFileUpload__SendTypeCase send_type_case;
  union {
    /*
     *文件信息
     */
    Iot__Service__FileTransport__ActionInFileUpload__FileInfo *file;
    /*
     *分块传输数据
     */
    ProtobufCBinaryData chunk;
    /*
     *文件传输结束
     */
    Iot__Service__FileTransport__ActionInFileUpload__Final *final;
  };
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_in_file_upload__descriptor) \
    , IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_UPLOAD__SEND_TYPE__NOT_SET, {0} }


struct  _Iot__Service__FileTransport__ActionOutFileUpload
{
  ProtobufCMessage base;
  /*
   *0-接收成功
   */
  uint32_t code;
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_UPLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_out_file_upload__descriptor) \
    , 0 }


struct  _Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo
{
  ProtobufCMessage base;
  /*
   *文件名
   */
  char *name;
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_DOWNLOAD__REQ_FILE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_in_file_download__req_file_info__descriptor) \
    , (char *)protobuf_c_empty_string }


typedef enum {
  IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_DOWNLOAD__MESSAGE__NOT_SET = 0,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_DOWNLOAD__MESSAGE_REQFILE = 1,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_DOWNLOAD__MESSAGE_CODE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_DOWNLOAD__MESSAGE)
} Iot__Service__FileTransport__ActionInFileDownload__MessageCase;

struct  _Iot__Service__FileTransport__ActionInFileDownload
{
  ProtobufCMessage base;
  Iot__Service__FileTransport__ActionInFileDownload__MessageCase message_case;
  union {
    /*
     *请求下载文件信息
     */
    Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo *reqfile;
    /*
     *0-接收成功
     */
    uint32_t code;
  };
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_DOWNLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_in_file_download__descriptor) \
    , IOT__SERVICE__FILE_TRANSPORT__ACTION_IN_FILE_DOWNLOAD__MESSAGE__NOT_SET, {0} }


struct  _Iot__Service__FileTransport__ActionOutFileDownload__FileInfo
{
  ProtobufCMessage base;
  /*
   *文件名
   */
  char *name;
  /*
   *文件大小，单位：Byte，-1表示未知大小
   */
  int64_t size;
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__FILE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_out_file_download__file_info__descriptor) \
    , (char *)protobuf_c_empty_string, 0 }


struct  _Iot__Service__FileTransport__ActionOutFileDownload__Final
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__FINAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_out_file_download__final__descriptor) \
     }


typedef enum {
  IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__MESSAGE__NOT_SET = 0,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__MESSAGE_FILE = 1,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__MESSAGE_CHUNK = 2,
  IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__MESSAGE_FINAL = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__MESSAGE)
} Iot__Service__FileTransport__ActionOutFileDownload__MessageCase;

struct  _Iot__Service__FileTransport__ActionOutFileDownload
{
  ProtobufCMessage base;
  Iot__Service__FileTransport__ActionOutFileDownload__MessageCase message_case;
  union {
    /*
     *文件信息
     */
    Iot__Service__FileTransport__ActionOutFileDownload__FileInfo *file;
    /*
     *分块传输数据
     */
    ProtobufCBinaryData chunk;
    /*
     *文件传输结束
     */
    Iot__Service__FileTransport__ActionOutFileDownload__Final *final;
  };
};
#define IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__action_out_file_download__descriptor) \
    , IOT__SERVICE__FILE_TRANSPORT__ACTION_OUT_FILE_DOWNLOAD__MESSAGE__NOT_SET, {0} }


struct  _Iot__Service__FileTransport__Properties
{
  ProtobufCMessage base;
};
#define IOT__SERVICE__FILE_TRANSPORT__PROPERTIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__file_transport__properties__descriptor) \
     }


/* Iot__Service__FileTransport__ActionInFileUpload__FileInfo methods */
void   iot__service__file_transport__action_in_file_upload__file_info__init
                     (Iot__Service__FileTransport__ActionInFileUpload__FileInfo         *message);
/* Iot__Service__FileTransport__ActionInFileUpload__Final methods */
void   iot__service__file_transport__action_in_file_upload__final__init
                     (Iot__Service__FileTransport__ActionInFileUpload__Final         *message);
/* Iot__Service__FileTransport__ActionInFileUpload methods */
void   iot__service__file_transport__action_in_file_upload__init
                     (Iot__Service__FileTransport__ActionInFileUpload         *message);
size_t iot__service__file_transport__action_in_file_upload__get_packed_size
                     (const Iot__Service__FileTransport__ActionInFileUpload   *message);
size_t iot__service__file_transport__action_in_file_upload__pack
                     (const Iot__Service__FileTransport__ActionInFileUpload   *message,
                      uint8_t             *out);
size_t iot__service__file_transport__action_in_file_upload__pack_to_buffer
                     (const Iot__Service__FileTransport__ActionInFileUpload   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__FileTransport__ActionInFileUpload *
       iot__service__file_transport__action_in_file_upload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__file_transport__action_in_file_upload__free_unpacked
                     (Iot__Service__FileTransport__ActionInFileUpload *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__FileTransport__ActionOutFileUpload methods */
void   iot__service__file_transport__action_out_file_upload__init
                     (Iot__Service__FileTransport__ActionOutFileUpload         *message);
size_t iot__service__file_transport__action_out_file_upload__get_packed_size
                     (const Iot__Service__FileTransport__ActionOutFileUpload   *message);
size_t iot__service__file_transport__action_out_file_upload__pack
                     (const Iot__Service__FileTransport__ActionOutFileUpload   *message,
                      uint8_t             *out);
size_t iot__service__file_transport__action_out_file_upload__pack_to_buffer
                     (const Iot__Service__FileTransport__ActionOutFileUpload   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__FileTransport__ActionOutFileUpload *
       iot__service__file_transport__action_out_file_upload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__file_transport__action_out_file_upload__free_unpacked
                     (Iot__Service__FileTransport__ActionOutFileUpload *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo methods */
void   iot__service__file_transport__action_in_file_download__req_file_info__init
                     (Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo         *message);
/* Iot__Service__FileTransport__ActionInFileDownload methods */
void   iot__service__file_transport__action_in_file_download__init
                     (Iot__Service__FileTransport__ActionInFileDownload         *message);
size_t iot__service__file_transport__action_in_file_download__get_packed_size
                     (const Iot__Service__FileTransport__ActionInFileDownload   *message);
size_t iot__service__file_transport__action_in_file_download__pack
                     (const Iot__Service__FileTransport__ActionInFileDownload   *message,
                      uint8_t             *out);
size_t iot__service__file_transport__action_in_file_download__pack_to_buffer
                     (const Iot__Service__FileTransport__ActionInFileDownload   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__FileTransport__ActionInFileDownload *
       iot__service__file_transport__action_in_file_download__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__file_transport__action_in_file_download__free_unpacked
                     (Iot__Service__FileTransport__ActionInFileDownload *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__FileTransport__ActionOutFileDownload__FileInfo methods */
void   iot__service__file_transport__action_out_file_download__file_info__init
                     (Iot__Service__FileTransport__ActionOutFileDownload__FileInfo         *message);
/* Iot__Service__FileTransport__ActionOutFileDownload__Final methods */
void   iot__service__file_transport__action_out_file_download__final__init
                     (Iot__Service__FileTransport__ActionOutFileDownload__Final         *message);
/* Iot__Service__FileTransport__ActionOutFileDownload methods */
void   iot__service__file_transport__action_out_file_download__init
                     (Iot__Service__FileTransport__ActionOutFileDownload         *message);
size_t iot__service__file_transport__action_out_file_download__get_packed_size
                     (const Iot__Service__FileTransport__ActionOutFileDownload   *message);
size_t iot__service__file_transport__action_out_file_download__pack
                     (const Iot__Service__FileTransport__ActionOutFileDownload   *message,
                      uint8_t             *out);
size_t iot__service__file_transport__action_out_file_download__pack_to_buffer
                     (const Iot__Service__FileTransport__ActionOutFileDownload   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__FileTransport__ActionOutFileDownload *
       iot__service__file_transport__action_out_file_download__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__file_transport__action_out_file_download__free_unpacked
                     (Iot__Service__FileTransport__ActionOutFileDownload *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__FileTransport__Properties methods */
void   iot__service__file_transport__properties__init
                     (Iot__Service__FileTransport__Properties         *message);
size_t iot__service__file_transport__properties__get_packed_size
                     (const Iot__Service__FileTransport__Properties   *message);
size_t iot__service__file_transport__properties__pack
                     (const Iot__Service__FileTransport__Properties   *message,
                      uint8_t             *out);
size_t iot__service__file_transport__properties__pack_to_buffer
                     (const Iot__Service__FileTransport__Properties   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__FileTransport__Properties *
       iot__service__file_transport__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__file_transport__properties__free_unpacked
                     (Iot__Service__FileTransport__Properties *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Iot__Service__FileTransport__ActionInFileUpload__FileInfo_Closure)
                 (const Iot__Service__FileTransport__ActionInFileUpload__FileInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionInFileUpload__Final_Closure)
                 (const Iot__Service__FileTransport__ActionInFileUpload__Final *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionInFileUpload_Closure)
                 (const Iot__Service__FileTransport__ActionInFileUpload *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionOutFileUpload_Closure)
                 (const Iot__Service__FileTransport__ActionOutFileUpload *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo_Closure)
                 (const Iot__Service__FileTransport__ActionInFileDownload__ReqFileInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionInFileDownload_Closure)
                 (const Iot__Service__FileTransport__ActionInFileDownload *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionOutFileDownload__FileInfo_Closure)
                 (const Iot__Service__FileTransport__ActionOutFileDownload__FileInfo *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionOutFileDownload__Final_Closure)
                 (const Iot__Service__FileTransport__ActionOutFileDownload__Final *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__ActionOutFileDownload_Closure)
                 (const Iot__Service__FileTransport__ActionOutFileDownload *message,
                  void *closure_data);
typedef void (*Iot__Service__FileTransport__Properties_Closure)
                 (const Iot__Service__FileTransport__Properties *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor iot__service__file_transport__action_in_file_upload__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_in_file_upload__file_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_in_file_upload__final__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_out_file_upload__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_in_file_download__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_in_file_download__req_file_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_out_file_download__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_out_file_download__file_info__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__action_out_file_download__final__descriptor;
extern const ProtobufCMessageDescriptor iot__service__file_transport__properties__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_fileTransport_2eproto__INCLUDED */
