/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: freezer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "freezer.pb-c.h"
void   iot__service__freezer__properties__init
                     (Iot__Service__Freezer__Properties         *message)
{
  static const Iot__Service__Freezer__Properties init_value = IOT__SERVICE__FREEZER__PROPERTIES__INIT;
  *message = init_value;
}
size_t iot__service__freezer__properties__get_packed_size
                     (const Iot__Service__Freezer__Properties *message)
{
  assert(message->base.descriptor == &iot__service__freezer__properties__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t iot__service__freezer__properties__pack
                     (const Iot__Service__Freezer__Properties *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &iot__service__freezer__properties__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t iot__service__freezer__properties__pack_to_buffer
                     (const Iot__Service__Freezer__Properties *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &iot__service__freezer__properties__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Iot__Service__Freezer__Properties *
       iot__service__freezer__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Iot__Service__Freezer__Properties *)
     protobuf_c_message_unpack (&iot__service__freezer__properties__descriptor,
                                allocator, len, data);
}
void   iot__service__freezer__properties__free_unpacked
                     (Iot__Service__Freezer__Properties *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &iot__service__freezer__properties__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor iot__service__freezer__properties__field_descriptors[9] =
{
  {
    "power",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "devLable",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, devlable),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "currentTemperature",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, currenttemperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetTemperature",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, targettemperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freezerLevel",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, freezerlevel),
    &iot__service__freezer__freezer_level__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quickFreezingMode",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, quickfreezingmode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extremeFreezingMode",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, extremefreezingmode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temperatureControlSwitch",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, temperaturecontrolswitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fCompartmentPower",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Iot__Service__Freezer__Properties, fcompartmentpower),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned iot__service__freezer__properties__field_indices_by_name[] = {
  2,   /* field[2] = currentTemperature */
  1,   /* field[1] = devLable */
  6,   /* field[6] = extremeFreezingMode */
  8,   /* field[8] = fCompartmentPower */
  4,   /* field[4] = freezerLevel */
  0,   /* field[0] = power */
  5,   /* field[5] = quickFreezingMode */
  3,   /* field[3] = targetTemperature */
  7,   /* field[7] = temperatureControlSwitch */
};
static const ProtobufCIntRange iot__service__freezer__properties__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor iot__service__freezer__properties__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "iot.service.freezer.Properties",
  "Properties",
  "Iot__Service__Freezer__Properties",
  "iot.service.freezer",
  sizeof(Iot__Service__Freezer__Properties),
  9,
  iot__service__freezer__properties__field_descriptors,
  iot__service__freezer__properties__field_indices_by_name,
  1,  iot__service__freezer__properties__number_ranges,
  (ProtobufCMessageInit) iot__service__freezer__properties__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue iot__service__freezer__freezer_level__enum_values_by_number[6] =
{
  { "NONE", "IOT__SERVICE__FREEZER__FREEZER_LEVEL__NONE", 0 },
  { "LEVELONE", "IOT__SERVICE__FREEZER__FREEZER_LEVEL__LEVELONE", 1 },
  { "LEVELTWO", "IOT__SERVICE__FREEZER__FREEZER_LEVEL__LEVELTWO", 2 },
  { "LEVELTHREE", "IOT__SERVICE__FREEZER__FREEZER_LEVEL__LEVELTHREE", 3 },
  { "LEVELFOUR", "IOT__SERVICE__FREEZER__FREEZER_LEVEL__LEVELFOUR", 4 },
  { "LEVELFIVE", "IOT__SERVICE__FREEZER__FREEZER_LEVEL__LEVELFIVE", 5 },
};
static const ProtobufCIntRange iot__service__freezer__freezer_level__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex iot__service__freezer__freezer_level__enum_values_by_name[6] =
{
  { "LEVELFIVE", 5 },
  { "LEVELFOUR", 4 },
  { "LEVELONE", 1 },
  { "LEVELTHREE", 3 },
  { "LEVELTWO", 2 },
  { "NONE", 0 },
};
const ProtobufCEnumDescriptor iot__service__freezer__freezer_level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "iot.service.freezer.FreezerLevel",
  "FreezerLevel",
  "Iot__Service__Freezer__FreezerLevel",
  "iot.service.freezer",
  6,
  iot__service__freezer__freezer_level__enum_values_by_number,
  6,
  iot__service__freezer__freezer_level__enum_values_by_name,
  1,
  iot__service__freezer__freezer_level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
