/* Generated by the heythings model compiler.  DO NOT EDIT! */
/* Generated from: wifiManage.proto */

#include <errno.h>
#include <assert.h>
#include "wifiManage.pb-c.h"
#include "wifi_manage_service.h"
#include "hey/schema.h"

#define WIFI_MANAGE_SERVICE (69 * 256)
#define PROP_IID_CNT 3
#define ACT_IID_CNT 1

static const struct hey_schema_property wifi_manage_properties_iids[] = {
    [0] = { .iid = 1, .type = HEY_PROPERTY_TYPE_GENERIC },
    [1] = { .iid = 2, .type = HEY_PROPERTY_TYPE_ARRAY },
    [2] = { .iid = 3, .type = HEY_PROPERTY_TYPE_ARRAY },
};
static struct hey_service *wifi_manage_service;

static int32_t action_get_ssid_list_start_cb(void *cb_data, struct hey_action_ctx *ctx, size_t len, uint8_t *value, void **user_context)
{
    int32_t ret = -1;
    Iot__Service__WifiManage__ActionInGetSsidList *get_ssid_list = iot__service__wifi_manage__action_in_get_ssid_list__unpack(NULL, len, value);
    if (NULL == get_ssid_list) {
        hey_action_stop(ctx);
        return EINVAL;
    }

    struct wifi_manage_get_ssid_list_in action = { 0 };
    ret = wifi_manage_get_ssid_list_start_cb(ctx, &action, user_context);

    iot__service__wifi_manage__action_in_get_ssid_list__free_unpacked(get_ssid_list, NULL);
    return ret;
}

static void action_get_ssid_list_stop_cb(void *cb_data, void *user_context)
{
    wifi_manage_get_ssid_list_stop_cb(user_context);
}

/**
 * @brief get ssid list action send message of wifi manage service
 * @param ctx      [action context]
 * @param action   [get ssid list action out]
 * @return int32_t [action send result, 0 means success]
 */
int32_t wifi_manage_get_ssid_list_send(struct hey_action_ctx *ctx, struct wifi_manage_get_ssid_list_out *action)
{
    int32_t ret = 0;
    Iot__Service__WifiManage__ActionOutGetSsidList *out = NULL;
    uint8_t *buf = NULL;
    out = malloc(sizeof(Iot__Service__WifiManage__ActionOutGetSsidList));
    if (NULL == out) {
        ret = ENOMEM;
        goto out;
    }
    iot__service__wifi_manage__action_out_get_ssid_list__init(out);
    if (action->n_ssidinfo) {
        out->n_ssidinfo  = action->n_ssidinfo;
        out->ssidinfo = calloc(out->n_ssidinfo, sizeof(Iot__Service__WifiManage__ActionOutGetSsidList__SsidInfo *));
        if (NULL == out->ssidinfo) {
            ret = ENOMEM;
            goto out;
        }
        for (int i = 0; i < out->n_ssidinfo; i++) {
            out->ssidinfo[i] = malloc(sizeof(Iot__Service__WifiManage__ActionOutGetSsidList__SsidInfo));
            if (NULL == out->ssidinfo[i]) {
                ret = ENOMEM;
                goto out;
            }
            iot__service__wifi_manage__action_out_get_ssid_list__ssid_info__init(out->ssidinfo[i]);
            out->ssidinfo[i]->ssid = action->ssidinfo[i]->ssid;
            out->ssidinfo[i]->rssi = action->ssidinfo[i]->rssi;
        }
    }
    size_t buf_len = iot__service__wifi_manage__action_out_get_ssid_list__get_packed_size(out);
    if (buf_len > 0) {
        buf = malloc(buf_len);
        if (NULL == buf) {
            ret = ENOMEM;
            goto out;
        }
    }
    iot__service__wifi_manage__action_out_get_ssid_list__pack(out, buf);
    ret = hey_action_msg_send(ctx, buf_len, buf);

out:
    if (out && out->ssidinfo) {
        for (int i = 0; i < out->n_ssidinfo; i++) {
            if (out->ssidinfo[i] == NULL)
                break;
            free(out->ssidinfo[i]);
        }
        free(out->ssidinfo);
    }
    free(out);
    free(buf);
    return ret;
}

/**
 * @brief get ssid list action stop of wifi manage service
 * @param ctx      [action context]
 * @return int32_t [action stop result, 0 means success]
 */
int32_t wifi_manage_get_ssid_list_stop(struct hey_action_ctx *ctx)
{
    return hey_action_stop(ctx);
}

static Iot__Service__WifiManage__WifiAutoChange *_wifi_manage_wifi_auto_change = NULL;
struct wifi_manage_wifi_auto_change *wifi_manage_wifi_auto_change_unpack(const uint8_t *data, size_t len)
{
    _wifi_manage_wifi_auto_change = iot__service__wifi_manage__wifi_auto_change__unpack(NULL, len, data);
    if (NULL == _wifi_manage_wifi_auto_change) {
        return NULL;
    }
    struct wifi_manage_wifi_auto_change *hey_struct = malloc(sizeof(struct wifi_manage_wifi_auto_change));
    if (NULL == hey_struct) {
        goto out1;
    }
    hey_struct->ssid = _wifi_manage_wifi_auto_change->ssid;
    hey_struct->status = _wifi_manage_wifi_auto_change->status;
    return hey_struct;
out1:
    iot__service__wifi_manage__wifi_auto_change__free_unpacked(_wifi_manage_wifi_auto_change, NULL);
    return NULL;
}

void wifi_manage_wifi_auto_change_free_unpacked(struct wifi_manage_wifi_auto_change *data)
{
    assert(NULL != data);
    iot__service__wifi_manage__wifi_auto_change__free_unpacked(_wifi_manage_wifi_auto_change, NULL);
    free(data);
}

int32_t wifi_manage_wifi_auto_change_get_packed_size(const struct wifi_manage_wifi_auto_change *data)
{
    assert(data);
    int ret = 0;
    Iot__Service__WifiManage__WifiAutoChange *pb_struct = malloc(sizeof(Iot__Service__WifiManage__WifiAutoChange));
    if (pb_struct == NULL) {
        return -1;
    }
    iot__service__wifi_manage__wifi_auto_change__init(pb_struct);
    pb_struct->ssid = data->ssid;
    pb_struct->status = data->status;
    ret = iot__service__wifi_manage__wifi_auto_change__get_packed_size(pb_struct);
    free(pb_struct);
    return ret;
}

int32_t wifi_manage_wifi_auto_change_pack(const struct wifi_manage_wifi_auto_change *data, uint8_t *out)
{
    assert(data);
    int ret = 0;
    Iot__Service__WifiManage__WifiAutoChange *pb_struct = malloc(sizeof(Iot__Service__WifiManage__WifiAutoChange));
    if (pb_struct == NULL) {
        return -1;
    }
    iot__service__wifi_manage__wifi_auto_change__init(pb_struct);
    pb_struct->ssid = data->ssid;
    pb_struct->status = data->status;
    ret = iot__service__wifi_manage__wifi_auto_change__pack(pb_struct, out);
    free(pb_struct);
    return ret;
}

static Iot__Service__WifiManage__AutoChangeConfiguration *_wifi_manage_auto_change_configuration = NULL;
struct wifi_manage_auto_change_configuration *wifi_manage_auto_change_configuration_unpack(const uint8_t *data, size_t len)
{
    _wifi_manage_auto_change_configuration = iot__service__wifi_manage__auto_change_configuration__unpack(NULL, len, data);
    if (NULL == _wifi_manage_auto_change_configuration) {
        return NULL;
    }
    struct wifi_manage_auto_change_configuration *hey_struct = malloc(sizeof(struct wifi_manage_auto_change_configuration));
    if (NULL == hey_struct) {
        goto out1;
    }
    hey_struct->ssid = _wifi_manage_auto_change_configuration->ssid;
    hey_struct->password = _wifi_manage_auto_change_configuration->password;
    return hey_struct;
out1:
    iot__service__wifi_manage__auto_change_configuration__free_unpacked(_wifi_manage_auto_change_configuration, NULL);
    return NULL;
}

void wifi_manage_auto_change_configuration_free_unpacked(struct wifi_manage_auto_change_configuration *data)
{
    assert(NULL != data);
    iot__service__wifi_manage__auto_change_configuration__free_unpacked(_wifi_manage_auto_change_configuration, NULL);
    free(data);
}

int32_t wifi_manage_auto_change_configuration_get_packed_size(const struct wifi_manage_auto_change_configuration *data)
{
    assert(data);
    int ret = 0;
    Iot__Service__WifiManage__AutoChangeConfiguration *pb_struct = malloc(sizeof(Iot__Service__WifiManage__AutoChangeConfiguration));
    if (pb_struct == NULL) {
        return -1;
    }
    iot__service__wifi_manage__auto_change_configuration__init(pb_struct);
    pb_struct->ssid = data->ssid;
    pb_struct->password = data->password;
    ret = iot__service__wifi_manage__auto_change_configuration__get_packed_size(pb_struct);
    free(pb_struct);
    return ret;
}

int32_t wifi_manage_auto_change_configuration_pack(const struct wifi_manage_auto_change_configuration *data, uint8_t *out)
{
    assert(data);
    int ret = 0;
    Iot__Service__WifiManage__AutoChangeConfiguration *pb_struct = malloc(sizeof(Iot__Service__WifiManage__AutoChangeConfiguration));
    if (pb_struct == NULL) {
        return -1;
    }
    iot__service__wifi_manage__auto_change_configuration__init(pb_struct);
    pb_struct->ssid = data->ssid;
    pb_struct->password = data->password;
    ret = iot__service__wifi_manage__auto_change_configuration__pack(pb_struct, out);
    free(pb_struct);
    return ret;
}

static int32_t service_wifi_manage_properties_write_cb(void *cb_data, size_t n_iid, uint32_t *iids,
                                                       size_t len, uint8_t *value)
{
    Iot__Service__WifiManage__Properties *props = iot__service__wifi_manage__properties__unpack(NULL, len, value);
    if (NULL == props) {
        return EINVAL;
    }

    int32_t ret = 0;
    struct wifi_manage_properties properties = { 0 };
    struct hey_array_node **wifiautochange = NULL;
    struct hey_array_node **autochangeconfiguration = NULL;
    properties.wifiautochangeenable = props->wifiautochangeenable;
    if (props->n_wifiautochange) {
        wifiautochange = calloc(props->n_wifiautochange, sizeof(struct hey_array_node *));
        if (wifiautochange == NULL) {
            ret = ENOMEM;
            goto out;
        }
        for (int i = 0; i < props->n_wifiautochange; i++) {
            wifiautochange[i] = malloc(sizeof(struct hey_array_node));
            if (wifiautochange[i] == NULL) {
                ret = ENOMEM;
                goto out;
            }
            wifiautochange[i]->id = props->wifiautochange[i]->id;
            wifiautochange[i]->data.data = props->wifiautochange[i]->data.data;
            wifiautochange[i]->data.len = props->wifiautochange[i]->data.len;
        }
        properties.n_wifiautochange = props->n_wifiautochange;
        properties.wifiautochange = wifiautochange;
    }
    if (props->n_autochangeconfiguration) {
        autochangeconfiguration = calloc(props->n_autochangeconfiguration, sizeof(struct hey_array_node *));
        if (autochangeconfiguration == NULL) {
            ret = ENOMEM;
            goto out;
        }
        for (int i = 0; i < props->n_autochangeconfiguration; i++) {
            autochangeconfiguration[i] = malloc(sizeof(struct hey_array_node));
            if (autochangeconfiguration[i] == NULL) {
                ret = ENOMEM;
                goto out;
            }
            autochangeconfiguration[i]->id = props->autochangeconfiguration[i]->id;
            autochangeconfiguration[i]->data.data = props->autochangeconfiguration[i]->data.data;
            autochangeconfiguration[i]->data.len = props->autochangeconfiguration[i]->data.len;
        }
        properties.n_autochangeconfiguration = props->n_autochangeconfiguration;
        properties.autochangeconfiguration = autochangeconfiguration;
    }
    ret = wifi_manage_properties_write_cb(n_iid, iids, &properties);

out:
    if (wifiautochange) {
        for (int i = 0; i < props->n_wifiautochange; i++) {
            free(wifiautochange[i]);
        }
        free(wifiautochange);
    }
    if (autochangeconfiguration) {
        for (int i = 0; i < props->n_autochangeconfiguration; i++) {
            free(autochangeconfiguration[i]);
        }
        free(autochangeconfiguration);
    }
    iot__service__wifi_manage__properties__free_unpacked(props, NULL);
    return ret;
}

static int32_t service_wifi_manage_properties_array_add_cb(void *cb_data, uint32_t iid, size_t len, uint8_t *value)
{
    switch(iid) {
    case WIFI_MANAGE_PROPERTY_WIFIAUTOCHANGE:
        return wifi_manage_wifiautochange_array_add_cb(len, value);
    case WIFI_MANAGE_PROPERTY_AUTOCHANGECONFIGURATION:
        return wifi_manage_autochangeconfiguration_array_add_cb(len, value);
    default:
        return -1;
    }
}

static int32_t service_wifi_manage_properties_array_del_cb(void *cb_data, uint32_t iid, size_t n_id, uint32_t *ids)
{
    switch(iid) {
    case WIFI_MANAGE_PROPERTY_WIFIAUTOCHANGE:
        return wifi_manage_wifiautochange_array_del_cb(n_id, ids);
    case WIFI_MANAGE_PROPERTY_AUTOCHANGECONFIGURATION:
        return wifi_manage_autochangeconfiguration_array_del_cb(n_id, ids);
    default:
        return -1;
    }
}

static int32_t service_wifi_manage_properties_array_replace_cb(void *cb_data, uint32_t iid, uint32_t id, size_t len, uint8_t *value)
{
    switch(iid) {
    case WIFI_MANAGE_PROPERTY_WIFIAUTOCHANGE:
        return wifi_manage_wifiautochange_array_replace_cb(id, len, value);
    case WIFI_MANAGE_PROPERTY_AUTOCHANGECONFIGURATION:
        return wifi_manage_autochangeconfiguration_array_replace_cb(id, len, value);
    default:
        return -1;
    }
}

static const struct hey_properties_callbacks props_cbs = {
    .write = service_wifi_manage_properties_write_cb,
    .array_add = service_wifi_manage_properties_array_add_cb,
    .array_del = service_wifi_manage_properties_array_del_cb,
    .array_replace = service_wifi_manage_properties_array_replace_cb,
};

static const struct hey_action_ctx_callbacks get_ssid_list_cbs = {
    .start = action_get_ssid_list_start_cb,
    .stop = action_get_ssid_list_stop_cb
};

static const struct hey_action_entry actions_iids[] = {
    [0] = { .iid = WIFI_MANAGE_ACTION_GET_SSID_LIST, .type = HEY_ACTION_ONCE, .cbs = &get_ssid_list_cbs },
};

static int wifi_manage_service_register(Iot__Service__WifiManage__Properties *props)
{
    uint8_t *buf;
    size_t buf_len;
    buf_len = iot__service__wifi_manage__properties__get_packed_size(props);
    if (buf_len == 0) {
        buf = NULL;
    } else {
        buf = malloc(buf_len);
        if (!buf) {
            return ENOMEM;
        }
        iot__service__wifi_manage__properties__pack(props, buf);
    }

    struct hey_schema_service schema_srv;
    hey_schema_service_init(&schema_srv);
    schema_srv.properties.iids = (struct hey_schema_property *)wifi_manage_properties_iids;
    schema_srv.properties.n_iid = PROP_IID_CNT;
    schema_srv.properties.value = buf;
    schema_srv.properties.len = buf_len;
    schema_srv.properties.cbs = &props_cbs;
    schema_srv.actions.iids = (struct hey_action_entry *)actions_iids;
    schema_srv.actions.n_iid = ACT_IID_CNT;
    wifi_manage_service = hey_service_register(WIFI_MANAGE_SERVICE, &schema_srv, NULL);
    if (NULL == wifi_manage_service) {
        free(buf);
        return errno;
    }

    free(buf);
    return 0;
}

/**
 * @brief update properties of wifi manage service
 * @param count      [the number of properties to be updated]
 * @param enumerate  [the iid enumeration of properties to be updated]
 * @param properties [properties structure with updated content]
 * @return int32_t   [update result]
 */
int32_t wifi_manage_properties_update(size_t count, uint32_t *enumerate, struct wifi_manage_properties *properties)
{
    assert(count <= PROP_IID_CNT);
    if (NULL == properties) {
        return EINVAL;
    }

    int ret = 0;
    Iot__Service__WifiManage__Properties *props = NULL;
    uint8_t *buf = NULL;
    ArrayNode **wifiautochange = NULL;
    ArrayNode **autochangeconfiguration = NULL;
    props = malloc(sizeof(Iot__Service__WifiManage__Properties));
    if (NULL == props) {
        ret = ENOMEM;
        goto out;
    }
    iot__service__wifi_manage__properties__init(props);
    if (properties->n_wifiautochange) {
        wifiautochange = calloc(properties->n_wifiautochange, sizeof(ArrayNode *));
        if (NULL == wifiautochange) {
            ret = ENOMEM;
            goto out;
        }
        for (int i = 0; i < properties->n_wifiautochange; i++) {
            wifiautochange[i] = malloc(sizeof(ArrayNode));
            if (NULL == wifiautochange[i]) {
                ret = ENOMEM;
                goto out;
            }
            array_node__init(wifiautochange[i]);
            wifiautochange[i]->id = properties->wifiautochange[i]->id;
            wifiautochange[i]->data.data = properties->wifiautochange[i]->data.data;
            wifiautochange[i]->data.len = properties->wifiautochange[i]->data.len;
        }
    }
    if (properties->n_autochangeconfiguration) {
        autochangeconfiguration = calloc(properties->n_autochangeconfiguration, sizeof(ArrayNode *));
        if (NULL == autochangeconfiguration) {
            ret = ENOMEM;
            goto out;
        }
        for (int i = 0; i < properties->n_autochangeconfiguration; i++) {
            autochangeconfiguration[i] = malloc(sizeof(ArrayNode));
            if (NULL == autochangeconfiguration[i]) {
                ret = ENOMEM;
                goto out;
            }
            array_node__init(autochangeconfiguration[i]);
            autochangeconfiguration[i]->id = properties->autochangeconfiguration[i]->id;
            autochangeconfiguration[i]->data.data = properties->autochangeconfiguration[i]->data.data;
            autochangeconfiguration[i]->data.len = properties->autochangeconfiguration[i]->data.len;
        }
    }
    props->wifiautochangeenable = properties->wifiautochangeenable;
    props->n_wifiautochange = properties->n_wifiautochange;
    props->wifiautochange = wifiautochange;
    props->n_autochangeconfiguration = properties->n_autochangeconfiguration;
    props->autochangeconfiguration = autochangeconfiguration;

    size_t buf_len;
    buf_len = iot__service__wifi_manage__properties__get_packed_size(props);
    if (buf_len > 0) {
        buf = malloc(buf_len);
        if (NULL == buf) {
            ret = ENOMEM;
            goto out;
        }
        iot__service__wifi_manage__properties__pack(props, buf);
    }

    struct hey_properties_content content = {
        .n_iid = count,
        .iids = enumerate,
        .len = buf_len,
        .value = buf
    };
    ret = hey_properties_update(wifi_manage_service, &content);

out:
    free(props);
    free(buf);
    if (wifiautochange) {
        for (int i = 0; i < properties->n_wifiautochange; i++) {
            free(wifiautochange[i]);
        }
        free(wifiautochange);
    }
    if (autochangeconfiguration) {
        for (int i = 0; i < properties->n_autochangeconfiguration; i++) {
            free(autochangeconfiguration[i]);
        }
        free(autochangeconfiguration);
    }
    return ret;
}

/**
 * @brief wifi manage service initialization
 * @param properties [wifi manage service properties]
 * @return int32_t   [initialize result]
*/
int32_t wifi_manage_service_init(const struct wifi_manage_properties *properties)
{
    int ret = 0;
    Iot__Service__WifiManage__Properties *props = NULL;
    ArrayNode **wifiautochange = NULL;
    ArrayNode **autochangeconfiguration = NULL;
    props = malloc(sizeof(Iot__Service__WifiManage__Properties));
    if (NULL == props) {
        ret = ENOMEM;
        goto out;
    }
    iot__service__wifi_manage__properties__init(props);
    if (NULL != properties) {
        if (properties->n_wifiautochange) {
            wifiautochange = calloc(properties->n_wifiautochange, sizeof(ArrayNode *));
            if (NULL == wifiautochange) {
                ret = ENOMEM;
                goto out;
            }
            for (int i = 0; i < properties->n_wifiautochange; i++) {
                wifiautochange[i] = malloc(sizeof(ArrayNode));
                if (NULL == wifiautochange[i]) {
                    ret = ENOMEM;
                    goto out;
                }
                array_node__init(wifiautochange[i]);
                wifiautochange[i]->id = properties->wifiautochange[i]->id;
                wifiautochange[i]->data.data = properties->wifiautochange[i]->data.data;
                wifiautochange[i]->data.len = properties->wifiautochange[i]->data.len;
            }
        }
        if (properties->n_autochangeconfiguration) {
            autochangeconfiguration = calloc(properties->n_autochangeconfiguration, sizeof(ArrayNode *));
            if (NULL == autochangeconfiguration) {
                ret = ENOMEM;
                goto out;
            }
            for (int i = 0; i < properties->n_autochangeconfiguration; i++) {
                autochangeconfiguration[i] = malloc(sizeof(ArrayNode));
                if (NULL == autochangeconfiguration[i]) {
                    ret = ENOMEM;
                    goto out;
                }
                array_node__init(autochangeconfiguration[i]);
                autochangeconfiguration[i]->id = properties->autochangeconfiguration[i]->id;
                autochangeconfiguration[i]->data.data = properties->autochangeconfiguration[i]->data.data;
                autochangeconfiguration[i]->data.len = properties->autochangeconfiguration[i]->data.len;
            }
        }
        props->wifiautochangeenable = properties->wifiautochangeenable;
        props->n_wifiautochange = properties->n_wifiautochange;
        props->wifiautochange = wifiautochange;
        props->n_autochangeconfiguration = properties->n_autochangeconfiguration;
        props->autochangeconfiguration = autochangeconfiguration;
    }

    ret = wifi_manage_service_register(props);

out:
    free(props);
    if (wifiautochange) {
        for (int i = 0; i < properties->n_wifiautochange; i++) {
            free(wifiautochange[i]);
        }
        free(wifiautochange);
    }
    if (autochangeconfiguration) {
        for (int i = 0; i < properties->n_autochangeconfiguration; i++) {
            free(autochangeconfiguration[i]);
        }
        free(autochangeconfiguration);
    }
    return ret;
}
