/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: deviceError.proto */

#ifndef PROTOBUF_C_deviceError_2eproto__INCLUDED
#define PROTOBUF_C_deviceError_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "schema/common/common.pb-c.h"

typedef struct _Iot__Service__DeviceError__ErrorNo Iot__Service__DeviceError__ErrorNo;
typedef struct _Iot__Service__DeviceError__CurrentErrorNo Iot__Service__DeviceError__CurrentErrorNo;
typedef struct _Iot__Service__DeviceError__EventDeviceFault Iot__Service__DeviceError__EventDeviceFault;
typedef struct _Iot__Service__DeviceError__EventDeviceMessage Iot__Service__DeviceError__EventDeviceMessage;
typedef struct _Iot__Service__DeviceError__EventDeviceAlert Iot__Service__DeviceError__EventDeviceAlert;
typedef struct _Iot__Service__DeviceError__Properties Iot__Service__DeviceError__Properties;


/* --- enums --- */


/* --- messages --- */

struct  _Iot__Service__DeviceError__ErrorNo
{
  ProtobufCMessage base;
  char *errorno;
  char *errorname;
};
#define IOT__SERVICE__DEVICE_ERROR__ERROR_NO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__device_error__error_no__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Iot__Service__DeviceError__CurrentErrorNo
{
  ProtobufCMessage base;
  char *time;
  char *errorno;
};
#define IOT__SERVICE__DEVICE_ERROR__CURRENT_ERROR_NO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__device_error__current_error_no__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  _Iot__Service__DeviceError__EventDeviceFault
{
  ProtobufCMessage base;
  char *faultno;
};
#define IOT__SERVICE__DEVICE_ERROR__EVENT_DEVICE_FAULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__device_error__event_device_fault__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Iot__Service__DeviceError__EventDeviceMessage
{
  ProtobufCMessage base;
  char *messageno;
};
#define IOT__SERVICE__DEVICE_ERROR__EVENT_DEVICE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__device_error__event_device_message__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Iot__Service__DeviceError__EventDeviceAlert
{
  ProtobufCMessage base;
  char *alertno;
};
#define IOT__SERVICE__DEVICE_ERROR__EVENT_DEVICE_ALERT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__device_error__event_device_alert__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  _Iot__Service__DeviceError__Properties
{
  ProtobufCMessage base;
  size_t n_errorno;
  ArrayNode **errorno;
  /*
   * event deviceFault (EventDeviceFault) = 3;
   * event deviceMessage(EventDeviceMessage) = 4;
   * event deviceAlert(EventDeviceAlert) = 5;
   */
  size_t n_currenterrorno;
  ArrayNode **currenterrorno;
};
#define IOT__SERVICE__DEVICE_ERROR__PROPERTIES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&iot__service__device_error__properties__descriptor) \
    , 0,NULL, 0,NULL }


/* Iot__Service__DeviceError__ErrorNo methods */
void   iot__service__device_error__error_no__init
                     (Iot__Service__DeviceError__ErrorNo         *message);
size_t iot__service__device_error__error_no__get_packed_size
                     (const Iot__Service__DeviceError__ErrorNo   *message);
size_t iot__service__device_error__error_no__pack
                     (const Iot__Service__DeviceError__ErrorNo   *message,
                      uint8_t             *out);
size_t iot__service__device_error__error_no__pack_to_buffer
                     (const Iot__Service__DeviceError__ErrorNo   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__DeviceError__ErrorNo *
       iot__service__device_error__error_no__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__device_error__error_no__free_unpacked
                     (Iot__Service__DeviceError__ErrorNo *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__DeviceError__CurrentErrorNo methods */
void   iot__service__device_error__current_error_no__init
                     (Iot__Service__DeviceError__CurrentErrorNo         *message);
size_t iot__service__device_error__current_error_no__get_packed_size
                     (const Iot__Service__DeviceError__CurrentErrorNo   *message);
size_t iot__service__device_error__current_error_no__pack
                     (const Iot__Service__DeviceError__CurrentErrorNo   *message,
                      uint8_t             *out);
size_t iot__service__device_error__current_error_no__pack_to_buffer
                     (const Iot__Service__DeviceError__CurrentErrorNo   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__DeviceError__CurrentErrorNo *
       iot__service__device_error__current_error_no__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__device_error__current_error_no__free_unpacked
                     (Iot__Service__DeviceError__CurrentErrorNo *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__DeviceError__EventDeviceFault methods */
void   iot__service__device_error__event_device_fault__init
                     (Iot__Service__DeviceError__EventDeviceFault         *message);
size_t iot__service__device_error__event_device_fault__get_packed_size
                     (const Iot__Service__DeviceError__EventDeviceFault   *message);
size_t iot__service__device_error__event_device_fault__pack
                     (const Iot__Service__DeviceError__EventDeviceFault   *message,
                      uint8_t             *out);
size_t iot__service__device_error__event_device_fault__pack_to_buffer
                     (const Iot__Service__DeviceError__EventDeviceFault   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__DeviceError__EventDeviceFault *
       iot__service__device_error__event_device_fault__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__device_error__event_device_fault__free_unpacked
                     (Iot__Service__DeviceError__EventDeviceFault *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__DeviceError__EventDeviceMessage methods */
void   iot__service__device_error__event_device_message__init
                     (Iot__Service__DeviceError__EventDeviceMessage         *message);
size_t iot__service__device_error__event_device_message__get_packed_size
                     (const Iot__Service__DeviceError__EventDeviceMessage   *message);
size_t iot__service__device_error__event_device_message__pack
                     (const Iot__Service__DeviceError__EventDeviceMessage   *message,
                      uint8_t             *out);
size_t iot__service__device_error__event_device_message__pack_to_buffer
                     (const Iot__Service__DeviceError__EventDeviceMessage   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__DeviceError__EventDeviceMessage *
       iot__service__device_error__event_device_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__device_error__event_device_message__free_unpacked
                     (Iot__Service__DeviceError__EventDeviceMessage *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__DeviceError__EventDeviceAlert methods */
void   iot__service__device_error__event_device_alert__init
                     (Iot__Service__DeviceError__EventDeviceAlert         *message);
size_t iot__service__device_error__event_device_alert__get_packed_size
                     (const Iot__Service__DeviceError__EventDeviceAlert   *message);
size_t iot__service__device_error__event_device_alert__pack
                     (const Iot__Service__DeviceError__EventDeviceAlert   *message,
                      uint8_t             *out);
size_t iot__service__device_error__event_device_alert__pack_to_buffer
                     (const Iot__Service__DeviceError__EventDeviceAlert   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__DeviceError__EventDeviceAlert *
       iot__service__device_error__event_device_alert__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__device_error__event_device_alert__free_unpacked
                     (Iot__Service__DeviceError__EventDeviceAlert *message,
                      ProtobufCAllocator *allocator);
/* Iot__Service__DeviceError__Properties methods */
void   iot__service__device_error__properties__init
                     (Iot__Service__DeviceError__Properties         *message);
size_t iot__service__device_error__properties__get_packed_size
                     (const Iot__Service__DeviceError__Properties   *message);
size_t iot__service__device_error__properties__pack
                     (const Iot__Service__DeviceError__Properties   *message,
                      uint8_t             *out);
size_t iot__service__device_error__properties__pack_to_buffer
                     (const Iot__Service__DeviceError__Properties   *message,
                      ProtobufCBuffer     *buffer);
Iot__Service__DeviceError__Properties *
       iot__service__device_error__properties__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   iot__service__device_error__properties__free_unpacked
                     (Iot__Service__DeviceError__Properties *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Iot__Service__DeviceError__ErrorNo_Closure)
                 (const Iot__Service__DeviceError__ErrorNo *message,
                  void *closure_data);
typedef void (*Iot__Service__DeviceError__CurrentErrorNo_Closure)
                 (const Iot__Service__DeviceError__CurrentErrorNo *message,
                  void *closure_data);
typedef void (*Iot__Service__DeviceError__EventDeviceFault_Closure)
                 (const Iot__Service__DeviceError__EventDeviceFault *message,
                  void *closure_data);
typedef void (*Iot__Service__DeviceError__EventDeviceMessage_Closure)
                 (const Iot__Service__DeviceError__EventDeviceMessage *message,
                  void *closure_data);
typedef void (*Iot__Service__DeviceError__EventDeviceAlert_Closure)
                 (const Iot__Service__DeviceError__EventDeviceAlert *message,
                  void *closure_data);
typedef void (*Iot__Service__DeviceError__Properties_Closure)
                 (const Iot__Service__DeviceError__Properties *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor iot__service__device_error__error_no__descriptor;
extern const ProtobufCMessageDescriptor iot__service__device_error__current_error_no__descriptor;
extern const ProtobufCMessageDescriptor iot__service__device_error__event_device_fault__descriptor;
extern const ProtobufCMessageDescriptor iot__service__device_error__event_device_message__descriptor;
extern const ProtobufCMessageDescriptor iot__service__device_error__event_device_alert__descriptor;
extern const ProtobufCMessageDescriptor iot__service__device_error__properties__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_deviceError_2eproto__INCLUDED */
